// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfflineConnector.proto

#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#include "OfflineConnector.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Schola {
PROTOBUF_CONSTEXPR OfflineDefinitionRequest::OfflineDefinitionRequest(
    ::_pbi::ConstantInitialized) {}
struct OfflineDefinitionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineDefinitionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineDefinitionRequestDefaultTypeInternal() {}
  union {
    OfflineDefinitionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineDefinitionRequestDefaultTypeInternal _OfflineDefinitionRequest_default_instance_;
PROTOBUF_CONSTEXPR OfflineDefinition::OfflineDefinition(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.definition_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OfflineDefinitionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineDefinitionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineDefinitionDefaultTypeInternal() {}
  union {
    OfflineDefinition _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineDefinitionDefaultTypeInternal _OfflineDefinition_default_instance_;
PROTOBUF_CONSTEXPR OfflineDataRequest::OfflineDataRequest(
    ::_pbi::ConstantInitialized) {}
struct OfflineDataRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineDataRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineDataRequestDefaultTypeInternal() {}
  union {
    OfflineDataRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineDataRequestDefaultTypeInternal _OfflineDataRequest_default_instance_;
PROTOBUF_CONSTEXPR OfflineData::OfflineData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.output_point_)*/nullptr
  , /*decltype(_impl_.optional_input_point_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct OfflineDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineDataDefaultTypeInternal() {}
  union {
    OfflineData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineDataDefaultTypeInternal _OfflineData_default_instance_;
PROTOBUF_CONSTEXPR BatchedOfflineData::BatchedOfflineData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BatchedOfflineDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchedOfflineDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchedOfflineDataDefaultTypeInternal() {}
  union {
    BatchedOfflineData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchedOfflineDataDefaultTypeInternal _BatchedOfflineData_default_instance_;
PROTOBUF_CONSTEXPR OfflineConnectorSettings_OptionsEntry_DoNotUse::OfflineConnectorSettings_OptionsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct OfflineConnectorSettings_OptionsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineConnectorSettings_OptionsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineConnectorSettings_OptionsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    OfflineConnectorSettings_OptionsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineConnectorSettings_OptionsEntry_DoNotUseDefaultTypeInternal _OfflineConnectorSettings_OptionsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR OfflineConnectorSettings::OfflineConnectorSettings(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.options_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.optional_seed_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct OfflineConnectorSettingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineConnectorSettingsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineConnectorSettingsDefaultTypeInternal() {}
  union {
    OfflineConnectorSettings _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineConnectorSettingsDefaultTypeInternal _OfflineConnectorSettings_default_instance_;
PROTOBUF_CONSTEXPR OfflineConnectorStartRequest::OfflineConnectorStartRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.settings_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OfflineConnectorStartRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineConnectorStartRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineConnectorStartRequestDefaultTypeInternal() {}
  union {
    OfflineConnectorStartRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineConnectorStartRequestDefaultTypeInternal _OfflineConnectorStartRequest_default_instance_;
PROTOBUF_CONSTEXPR OfflineConnectorStartResponse::OfflineConnectorStartResponse(
    ::_pbi::ConstantInitialized) {}
struct OfflineConnectorStartResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OfflineConnectorStartResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OfflineConnectorStartResponseDefaultTypeInternal() {}
  union {
    OfflineConnectorStartResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OfflineConnectorStartResponseDefaultTypeInternal _OfflineConnectorStartResponse_default_instance_;
}  // namespace Schola
static ::_pb::Metadata file_level_metadata_OfflineConnector_2eproto[9];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_OfflineConnector_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_OfflineConnector_2eproto = nullptr;

const uint32_t TableStruct_OfflineConnector_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineDefinitionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineDefinition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineDefinition, _impl_.definition_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineDataRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineData, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineData, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineData, _impl_.output_point_),
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineData, _impl_.optional_input_point_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::BatchedOfflineData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::BatchedOfflineData, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings, _impl_.options_),
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorSettings, _impl_.optional_seed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorStartRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorStartRequest, _impl_.settings_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::OfflineConnectorStartResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Schola::OfflineDefinitionRequest)},
  { 6, -1, -1, sizeof(::Schola::OfflineDefinition)},
  { 13, -1, -1, sizeof(::Schola::OfflineDataRequest)},
  { 19, -1, -1, sizeof(::Schola::OfflineData)},
  { 28, -1, -1, sizeof(::Schola::BatchedOfflineData)},
  { 35, 43, -1, sizeof(::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse)},
  { 45, -1, -1, sizeof(::Schola::OfflineConnectorSettings)},
  { 54, -1, -1, sizeof(::Schola::OfflineConnectorStartRequest)},
  { 61, -1, -1, sizeof(::Schola::OfflineConnectorStartResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Schola::_OfflineDefinitionRequest_default_instance_._instance,
  &::Schola::_OfflineDefinition_default_instance_._instance,
  &::Schola::_OfflineDataRequest_default_instance_._instance,
  &::Schola::_OfflineData_default_instance_._instance,
  &::Schola::_BatchedOfflineData_default_instance_._instance,
  &::Schola::_OfflineConnectorSettings_OptionsEntry_DoNotUse_default_instance_._instance,
  &::Schola::_OfflineConnectorSettings_default_instance_._instance,
  &::Schola::_OfflineConnectorStartRequest_default_instance_._instance,
  &::Schola::_OfflineConnectorStartResponse_default_instance_._instance,
};

const char descriptor_table_protodef_OfflineConnector_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026OfflineConnector.proto\022\006Schola\032\021Defini"
  "tions.proto\032\013State.proto\032\022StateUpdates.p"
  "roto\032\014Points.proto\032\014Spaces.proto\"\032\n\030Offl"
  "ineDefinitionRequest\"6\n\021OfflineDefinitio"
  "n\022!\n\ndefinition\030\001 \003(\0132\r.Schola.Space\"\024\n\022"
  "OfflineDataRequest\"p\n\013OfflineData\022#\n\014out"
  "put_point\030\001 \001(\0132\r.Schola.Point\022$\n\013input_"
  "point\030\002 \001(\0132\r.Schola.PointH\000B\026\n\024optional"
  "_input_point\"7\n\022BatchedOfflineData\022!\n\004da"
  "ta\030\001 \003(\0132\023.Schola.OfflineData\"\253\001\n\030Offlin"
  "eConnectorSettings\022\016\n\004seed\030\001 \001(\005H\000\022>\n\007op"
  "tions\030\002 \003(\0132-.Schola.OfflineConnectorSet"
  "tings.OptionsEntry\032.\n\014OptionsEntry\022\013\n\003ke"
  "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\017\n\roptional_s"
  "eed\"R\n\034OfflineConnectorStartRequest\0222\n\010s"
  "ettings\030\001 \003(\0132 .Schola.OfflineConnectorS"
  "ettings\"\037\n\035OfflineConnectorStartResponse"
  "2\221\002\n\027OfflineConnectorService\022E\n\013RequestD"
  "ata\022\032.Schola.OfflineDataRequest\032\032.Schola"
  ".BatchedOfflineData\022P\n\021RequestDefinition"
  "\022 .Schola.OfflineDefinitionRequest\032\031.Sch"
  "ola.OfflineDefinition\022]\n\016StartConnector\022"
  "$.Schola.OfflineConnectorStartRequest\032%."
  "Schola.OfflineConnectorStartResponseb\006pr"
  "oto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_OfflineConnector_2eproto_deps[5] = {
  &::descriptor_table_Definitions_2eproto,
  &::descriptor_table_Points_2eproto,
  &::descriptor_table_Spaces_2eproto,
  &::descriptor_table_State_2eproto,
  &::descriptor_table_StateUpdates_2eproto,
};
static ::_pbi::once_flag descriptor_table_OfflineConnector_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_OfflineConnector_2eproto = {
    false, false, 964, descriptor_table_protodef_OfflineConnector_2eproto,
    "OfflineConnector.proto",
    &descriptor_table_OfflineConnector_2eproto_once, descriptor_table_OfflineConnector_2eproto_deps, 5, 9,
    schemas, file_default_instances, TableStruct_OfflineConnector_2eproto::offsets,
    file_level_metadata_OfflineConnector_2eproto, file_level_enum_descriptors_OfflineConnector_2eproto,
    file_level_service_descriptors_OfflineConnector_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_OfflineConnector_2eproto_getter() {
  return &descriptor_table_OfflineConnector_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_OfflineConnector_2eproto(&descriptor_table_OfflineConnector_2eproto);
namespace Schola {

// ===================================================================

class OfflineDefinitionRequest::_Internal {
 public:
};

OfflineDefinitionRequest::OfflineDefinitionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Schola.OfflineDefinitionRequest)
}
OfflineDefinitionRequest::OfflineDefinitionRequest(const OfflineDefinitionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  OfflineDefinitionRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.OfflineDefinitionRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OfflineDefinitionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OfflineDefinitionRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata OfflineDefinitionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[0]);
}

// ===================================================================

class OfflineDefinition::_Internal {
 public:
};

void OfflineDefinition::clear_definition() {
  _impl_.definition_.Clear();
}
OfflineDefinition::OfflineDefinition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.OfflineDefinition)
}
OfflineDefinition::OfflineDefinition(const OfflineDefinition& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OfflineDefinition* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.definition_){from._impl_.definition_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.OfflineDefinition)
}

inline void OfflineDefinition::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.definition_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

OfflineDefinition::~OfflineDefinition() {
  // @@protoc_insertion_point(destructor:Schola.OfflineDefinition)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OfflineDefinition::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.definition_.~RepeatedPtrField();
}

void OfflineDefinition::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OfflineDefinition::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.OfflineDefinition)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.definition_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OfflineDefinition::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Schola.Space definition = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_definition(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OfflineDefinition::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.OfflineDefinition)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Schola.Space definition = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_definition_size()); i < n; i++) {
    const auto& repfield = this->_internal_definition(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.OfflineDefinition)
  return target;
}

size_t OfflineDefinition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.OfflineDefinition)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Schola.Space definition = 1;
  total_size += 1UL * this->_internal_definition_size();
  for (const auto& msg : this->_impl_.definition_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OfflineDefinition::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OfflineDefinition::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OfflineDefinition::GetClassData() const { return &_class_data_; }


void OfflineDefinition::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OfflineDefinition*>(&to_msg);
  auto& from = static_cast<const OfflineDefinition&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.OfflineDefinition)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.definition_.MergeFrom(from._impl_.definition_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OfflineDefinition::CopyFrom(const OfflineDefinition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.OfflineDefinition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OfflineDefinition::IsInitialized() const {
  return true;
}

void OfflineDefinition::InternalSwap(OfflineDefinition* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.definition_.InternalSwap(&other->_impl_.definition_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OfflineDefinition::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[1]);
}

// ===================================================================

class OfflineDataRequest::_Internal {
 public:
};

OfflineDataRequest::OfflineDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Schola.OfflineDataRequest)
}
OfflineDataRequest::OfflineDataRequest(const OfflineDataRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  OfflineDataRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.OfflineDataRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OfflineDataRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OfflineDataRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata OfflineDataRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[2]);
}

// ===================================================================

class OfflineData::_Internal {
 public:
  static const ::Schola::Point& output_point(const OfflineData* msg);
  static const ::Schola::Point& input_point(const OfflineData* msg);
};

const ::Schola::Point&
OfflineData::_Internal::output_point(const OfflineData* msg) {
  return *msg->_impl_.output_point_;
}
const ::Schola::Point&
OfflineData::_Internal::input_point(const OfflineData* msg) {
  return *msg->_impl_.optional_input_point_.input_point_;
}
void OfflineData::clear_output_point() {
  if (GetArenaForAllocation() == nullptr && _impl_.output_point_ != nullptr) {
    delete _impl_.output_point_;
  }
  _impl_.output_point_ = nullptr;
}
void OfflineData::set_allocated_input_point(::Schola::Point* input_point) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_optional_input_point();
  if (input_point) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(input_point));
    if (message_arena != submessage_arena) {
      input_point = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, input_point, submessage_arena);
    }
    set_has_input_point();
    _impl_.optional_input_point_.input_point_ = input_point;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.OfflineData.input_point)
}
void OfflineData::clear_input_point() {
  if (_internal_has_input_point()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.optional_input_point_.input_point_;
    }
    clear_has_optional_input_point();
  }
}
OfflineData::OfflineData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.OfflineData)
}
OfflineData::OfflineData(const OfflineData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OfflineData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.output_point_){nullptr}
    , decltype(_impl_.optional_input_point_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_output_point()) {
    _this->_impl_.output_point_ = new ::Schola::Point(*from._impl_.output_point_);
  }
  clear_has_optional_input_point();
  switch (from.optional_input_point_case()) {
    case kInputPoint: {
      _this->_internal_mutable_input_point()->::Schola::Point::MergeFrom(
          from._internal_input_point());
      break;
    }
    case OPTIONAL_INPUT_POINT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Schola.OfflineData)
}

inline void OfflineData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.output_point_){nullptr}
    , decltype(_impl_.optional_input_point_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_optional_input_point();
}

OfflineData::~OfflineData() {
  // @@protoc_insertion_point(destructor:Schola.OfflineData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OfflineData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.output_point_;
  if (has_optional_input_point()) {
    clear_optional_input_point();
  }
}

void OfflineData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OfflineData::clear_optional_input_point() {
// @@protoc_insertion_point(one_of_clear_start:Schola.OfflineData)
  switch (optional_input_point_case()) {
    case kInputPoint: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.optional_input_point_.input_point_;
      }
      break;
    }
    case OPTIONAL_INPUT_POINT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = OPTIONAL_INPUT_POINT_NOT_SET;
}


void OfflineData::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.OfflineData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.output_point_ != nullptr) {
    delete _impl_.output_point_;
  }
  _impl_.output_point_ = nullptr;
  clear_optional_input_point();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OfflineData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Schola.Point output_point = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_output_point(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.Point input_point = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_input_point(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OfflineData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.OfflineData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Schola.Point output_point = 1;
  if (this->_internal_has_output_point()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::output_point(this),
        _Internal::output_point(this).GetCachedSize(), target, stream);
  }

  // .Schola.Point input_point = 2;
  if (_internal_has_input_point()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::input_point(this),
        _Internal::input_point(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.OfflineData)
  return target;
}

size_t OfflineData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.OfflineData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Schola.Point output_point = 1;
  if (this->_internal_has_output_point()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.output_point_);
  }

  switch (optional_input_point_case()) {
    // .Schola.Point input_point = 2;
    case kInputPoint: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.optional_input_point_.input_point_);
      break;
    }
    case OPTIONAL_INPUT_POINT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OfflineData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OfflineData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OfflineData::GetClassData() const { return &_class_data_; }


void OfflineData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OfflineData*>(&to_msg);
  auto& from = static_cast<const OfflineData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.OfflineData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_output_point()) {
    _this->_internal_mutable_output_point()->::Schola::Point::MergeFrom(
        from._internal_output_point());
  }
  switch (from.optional_input_point_case()) {
    case kInputPoint: {
      _this->_internal_mutable_input_point()->::Schola::Point::MergeFrom(
          from._internal_input_point());
      break;
    }
    case OPTIONAL_INPUT_POINT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OfflineData::CopyFrom(const OfflineData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.OfflineData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OfflineData::IsInitialized() const {
  return true;
}

void OfflineData::InternalSwap(OfflineData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.output_point_, other->_impl_.output_point_);
  swap(_impl_.optional_input_point_, other->_impl_.optional_input_point_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata OfflineData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[3]);
}

// ===================================================================

class BatchedOfflineData::_Internal {
 public:
};

BatchedOfflineData::BatchedOfflineData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.BatchedOfflineData)
}
BatchedOfflineData::BatchedOfflineData(const BatchedOfflineData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BatchedOfflineData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.BatchedOfflineData)
}

inline void BatchedOfflineData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BatchedOfflineData::~BatchedOfflineData() {
  // @@protoc_insertion_point(destructor:Schola.BatchedOfflineData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BatchedOfflineData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedPtrField();
}

void BatchedOfflineData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BatchedOfflineData::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.BatchedOfflineData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BatchedOfflineData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Schola.OfflineData data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BatchedOfflineData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.BatchedOfflineData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Schola.OfflineData data = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_data_size()); i < n; i++) {
    const auto& repfield = this->_internal_data(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.BatchedOfflineData)
  return target;
}

size_t BatchedOfflineData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.BatchedOfflineData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Schola.OfflineData data = 1;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->_impl_.data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BatchedOfflineData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BatchedOfflineData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BatchedOfflineData::GetClassData() const { return &_class_data_; }


void BatchedOfflineData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BatchedOfflineData*>(&to_msg);
  auto& from = static_cast<const BatchedOfflineData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.BatchedOfflineData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BatchedOfflineData::CopyFrom(const BatchedOfflineData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.BatchedOfflineData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchedOfflineData::IsInitialized() const {
  return true;
}

void BatchedOfflineData::InternalSwap(BatchedOfflineData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BatchedOfflineData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[4]);
}

// ===================================================================

OfflineConnectorSettings_OptionsEntry_DoNotUse::OfflineConnectorSettings_OptionsEntry_DoNotUse() {}
OfflineConnectorSettings_OptionsEntry_DoNotUse::OfflineConnectorSettings_OptionsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void OfflineConnectorSettings_OptionsEntry_DoNotUse::MergeFrom(const OfflineConnectorSettings_OptionsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata OfflineConnectorSettings_OptionsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[5]);
}

// ===================================================================

class OfflineConnectorSettings::_Internal {
 public:
};

OfflineConnectorSettings::OfflineConnectorSettings(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &OfflineConnectorSettings::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.OfflineConnectorSettings)
}
OfflineConnectorSettings::OfflineConnectorSettings(const OfflineConnectorSettings& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OfflineConnectorSettings* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.options_)*/{}
    , decltype(_impl_.optional_seed_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.options_.MergeFrom(from._impl_.options_);
  clear_has_optional_seed();
  switch (from.optional_seed_case()) {
    case kSeed: {
      _this->_internal_set_seed(from._internal_seed());
      break;
    }
    case OPTIONAL_SEED_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Schola.OfflineConnectorSettings)
}

inline void OfflineConnectorSettings::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.options_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.optional_seed_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_optional_seed();
}

OfflineConnectorSettings::~OfflineConnectorSettings() {
  // @@protoc_insertion_point(destructor:Schola.OfflineConnectorSettings)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void OfflineConnectorSettings::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.options_.Destruct();
  _impl_.options_.~MapField();
  if (has_optional_seed()) {
    clear_optional_seed();
  }
}

void OfflineConnectorSettings::ArenaDtor(void* object) {
  OfflineConnectorSettings* _this = reinterpret_cast< OfflineConnectorSettings* >(object);
  _this->_impl_.options_.Destruct();
}
void OfflineConnectorSettings::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OfflineConnectorSettings::clear_optional_seed() {
// @@protoc_insertion_point(one_of_clear_start:Schola.OfflineConnectorSettings)
  switch (optional_seed_case()) {
    case kSeed: {
      // No need to clear
      break;
    }
    case OPTIONAL_SEED_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = OPTIONAL_SEED_NOT_SET;
}


void OfflineConnectorSettings::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.OfflineConnectorSettings)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.options_.Clear();
  clear_optional_seed();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OfflineConnectorSettings::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 seed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _internal_set_seed(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, string> options = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.options_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OfflineConnectorSettings::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.OfflineConnectorSettings)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 seed = 1;
  if (_internal_has_seed()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_seed(), target);
  }

  // map<string, string> options = 2;
  if (!this->_internal_options().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = OfflineConnectorSettings_OptionsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_options();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.OfflineConnectorSettings.OptionsEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.OfflineConnectorSettings.OptionsEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(2, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(2, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.OfflineConnectorSettings)
  return target;
}

size_t OfflineConnectorSettings::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.OfflineConnectorSettings)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> options = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_options_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_options().begin();
      it != this->_internal_options().end(); ++it) {
    total_size += OfflineConnectorSettings_OptionsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  switch (optional_seed_case()) {
    // int32 seed = 1;
    case kSeed: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_seed());
      break;
    }
    case OPTIONAL_SEED_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OfflineConnectorSettings::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OfflineConnectorSettings::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OfflineConnectorSettings::GetClassData() const { return &_class_data_; }


void OfflineConnectorSettings::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OfflineConnectorSettings*>(&to_msg);
  auto& from = static_cast<const OfflineConnectorSettings&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.OfflineConnectorSettings)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.options_.MergeFrom(from._impl_.options_);
  switch (from.optional_seed_case()) {
    case kSeed: {
      _this->_internal_set_seed(from._internal_seed());
      break;
    }
    case OPTIONAL_SEED_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OfflineConnectorSettings::CopyFrom(const OfflineConnectorSettings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.OfflineConnectorSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OfflineConnectorSettings::IsInitialized() const {
  return true;
}

void OfflineConnectorSettings::InternalSwap(OfflineConnectorSettings* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.options_.InternalSwap(&other->_impl_.options_);
  swap(_impl_.optional_seed_, other->_impl_.optional_seed_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata OfflineConnectorSettings::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[6]);
}

// ===================================================================

class OfflineConnectorStartRequest::_Internal {
 public:
};

OfflineConnectorStartRequest::OfflineConnectorStartRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.OfflineConnectorStartRequest)
}
OfflineConnectorStartRequest::OfflineConnectorStartRequest(const OfflineConnectorStartRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OfflineConnectorStartRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.settings_){from._impl_.settings_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.OfflineConnectorStartRequest)
}

inline void OfflineConnectorStartRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.settings_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

OfflineConnectorStartRequest::~OfflineConnectorStartRequest() {
  // @@protoc_insertion_point(destructor:Schola.OfflineConnectorStartRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OfflineConnectorStartRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.settings_.~RepeatedPtrField();
}

void OfflineConnectorStartRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OfflineConnectorStartRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.OfflineConnectorStartRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.settings_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OfflineConnectorStartRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Schola.OfflineConnectorSettings settings = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_settings(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OfflineConnectorStartRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.OfflineConnectorStartRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Schola.OfflineConnectorSettings settings = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_settings_size()); i < n; i++) {
    const auto& repfield = this->_internal_settings(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.OfflineConnectorStartRequest)
  return target;
}

size_t OfflineConnectorStartRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.OfflineConnectorStartRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Schola.OfflineConnectorSettings settings = 1;
  total_size += 1UL * this->_internal_settings_size();
  for (const auto& msg : this->_impl_.settings_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OfflineConnectorStartRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OfflineConnectorStartRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OfflineConnectorStartRequest::GetClassData() const { return &_class_data_; }


void OfflineConnectorStartRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OfflineConnectorStartRequest*>(&to_msg);
  auto& from = static_cast<const OfflineConnectorStartRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.OfflineConnectorStartRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.settings_.MergeFrom(from._impl_.settings_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OfflineConnectorStartRequest::CopyFrom(const OfflineConnectorStartRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.OfflineConnectorStartRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OfflineConnectorStartRequest::IsInitialized() const {
  return true;
}

void OfflineConnectorStartRequest::InternalSwap(OfflineConnectorStartRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.settings_.InternalSwap(&other->_impl_.settings_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OfflineConnectorStartRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[7]);
}

// ===================================================================

class OfflineConnectorStartResponse::_Internal {
 public:
};

OfflineConnectorStartResponse::OfflineConnectorStartResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Schola.OfflineConnectorStartResponse)
}
OfflineConnectorStartResponse::OfflineConnectorStartResponse(const OfflineConnectorStartResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  OfflineConnectorStartResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.OfflineConnectorStartResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OfflineConnectorStartResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OfflineConnectorStartResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata OfflineConnectorStartResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OfflineConnector_2eproto_getter, &descriptor_table_OfflineConnector_2eproto_once,
      file_level_metadata_OfflineConnector_2eproto[8]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Schola::OfflineDefinitionRequest*
Arena::CreateMaybeMessage< ::Schola::OfflineDefinitionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineDefinitionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::OfflineDefinition*
Arena::CreateMaybeMessage< ::Schola::OfflineDefinition >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineDefinition >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::OfflineDataRequest*
Arena::CreateMaybeMessage< ::Schola::OfflineDataRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineDataRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::OfflineData*
Arena::CreateMaybeMessage< ::Schola::OfflineData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineData >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::BatchedOfflineData*
Arena::CreateMaybeMessage< ::Schola::BatchedOfflineData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::BatchedOfflineData >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineConnectorSettings_OptionsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::OfflineConnectorSettings*
Arena::CreateMaybeMessage< ::Schola::OfflineConnectorSettings >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineConnectorSettings >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::OfflineConnectorStartRequest*
Arena::CreateMaybeMessage< ::Schola::OfflineConnectorStartRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineConnectorStartRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::OfflineConnectorStartResponse*
Arena::CreateMaybeMessage< ::Schola::OfflineConnectorStartResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::OfflineConnectorStartResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
