// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Spaces.proto

#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#include "Spaces.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Schola {
PROTOBUF_CONSTEXPR BoxSpace_BoxSpaceDimension::BoxSpace_BoxSpaceDimension(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.low_)*/0
  , /*decltype(_impl_.high_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BoxSpace_BoxSpaceDimensionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BoxSpace_BoxSpaceDimensionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BoxSpace_BoxSpaceDimensionDefaultTypeInternal() {}
  union {
    BoxSpace_BoxSpaceDimension _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BoxSpace_BoxSpaceDimensionDefaultTypeInternal _BoxSpace_BoxSpaceDimension_default_instance_;
PROTOBUF_CONSTEXPR BoxSpace::BoxSpace(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dimensions_)*/{}
  , /*decltype(_impl_.shape_dimensions_)*/{}
  , /*decltype(_impl_._shape_dimensions_cached_byte_size_)*/{0}
  , /*decltype(_impl_.dtype_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BoxSpaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BoxSpaceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BoxSpaceDefaultTypeInternal() {}
  union {
    BoxSpace _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BoxSpaceDefaultTypeInternal _BoxSpace_default_instance_;
PROTOBUF_CONSTEXPR DiscreteSpace::DiscreteSpace(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.high_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DiscreteSpaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DiscreteSpaceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DiscreteSpaceDefaultTypeInternal() {}
  union {
    DiscreteSpace _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DiscreteSpaceDefaultTypeInternal _DiscreteSpace_default_instance_;
PROTOBUF_CONSTEXPR MultiDiscreteSpace::MultiDiscreteSpace(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.high_)*/{}
  , /*decltype(_impl_._high_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MultiDiscreteSpaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MultiDiscreteSpaceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MultiDiscreteSpaceDefaultTypeInternal() {}
  union {
    MultiDiscreteSpace _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MultiDiscreteSpaceDefaultTypeInternal _MultiDiscreteSpace_default_instance_;
PROTOBUF_CONSTEXPR MultiBinarySpace::MultiBinarySpace(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.shape_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MultiBinarySpaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MultiBinarySpaceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MultiBinarySpaceDefaultTypeInternal() {}
  union {
    MultiBinarySpace _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MultiBinarySpaceDefaultTypeInternal _MultiBinarySpace_default_instance_;
PROTOBUF_CONSTEXPR Space::Space(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.space_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct SpaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpaceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpaceDefaultTypeInternal() {}
  union {
    Space _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpaceDefaultTypeInternal _Space_default_instance_;
PROTOBUF_CONSTEXPR DictSpace_SpacesEntry_DoNotUse::DictSpace_SpacesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct DictSpace_SpacesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DictSpace_SpacesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DictSpace_SpacesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    DictSpace_SpacesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DictSpace_SpacesEntry_DoNotUseDefaultTypeInternal _DictSpace_SpacesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR DictSpace::DictSpace(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.spaces_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DictSpaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DictSpaceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DictSpaceDefaultTypeInternal() {}
  union {
    DictSpace _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DictSpaceDefaultTypeInternal _DictSpace_default_instance_;
}  // namespace Schola
static ::_pb::Metadata file_level_metadata_Spaces_2eproto[8];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Spaces_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Spaces_2eproto = nullptr;

const uint32_t TableStruct_Spaces_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::BoxSpace_BoxSpaceDimension, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::BoxSpace_BoxSpaceDimension, _impl_.low_),
  PROTOBUF_FIELD_OFFSET(::Schola::BoxSpace_BoxSpaceDimension, _impl_.high_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::BoxSpace, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::BoxSpace, _impl_.dimensions_),
  PROTOBUF_FIELD_OFFSET(::Schola::BoxSpace, _impl_.shape_dimensions_),
  PROTOBUF_FIELD_OFFSET(::Schola::BoxSpace, _impl_.dtype_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::DiscreteSpace, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::DiscreteSpace, _impl_.high_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::MultiDiscreteSpace, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::MultiDiscreteSpace, _impl_.high_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::MultiBinarySpace, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::MultiBinarySpace, _impl_.shape_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::Space, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Schola::Space, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Schola::Space, _impl_.space_),
  PROTOBUF_FIELD_OFFSET(::Schola::DictSpace_SpacesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::DictSpace_SpacesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::DictSpace_SpacesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::DictSpace_SpacesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::DictSpace, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::DictSpace, _impl_.spaces_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Schola::BoxSpace_BoxSpaceDimension)},
  { 8, -1, -1, sizeof(::Schola::BoxSpace)},
  { 17, -1, -1, sizeof(::Schola::DiscreteSpace)},
  { 24, -1, -1, sizeof(::Schola::MultiDiscreteSpace)},
  { 31, -1, -1, sizeof(::Schola::MultiBinarySpace)},
  { 38, -1, -1, sizeof(::Schola::Space)},
  { 50, 58, -1, sizeof(::Schola::DictSpace_SpacesEntry_DoNotUse)},
  { 60, -1, -1, sizeof(::Schola::DictSpace)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Schola::_BoxSpace_BoxSpaceDimension_default_instance_._instance,
  &::Schola::_BoxSpace_default_instance_._instance,
  &::Schola::_DiscreteSpace_default_instance_._instance,
  &::Schola::_MultiDiscreteSpace_default_instance_._instance,
  &::Schola::_MultiBinarySpace_default_instance_._instance,
  &::Schola::_Space_default_instance_._instance,
  &::Schola::_DictSpace_SpacesEntry_DoNotUse_default_instance_._instance,
  &::Schola::_DictSpace_default_instance_._instance,
};

const char descriptor_table_protodef_Spaces_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Spaces.proto\022\006Schola\032\013DType.proto\"\252\001\n\010"
  "BoxSpace\0226\n\ndimensions\030\001 \003(\0132\".Schola.Bo"
  "xSpace.BoxSpaceDimension\022\030\n\020shape_dimens"
  "ions\030\002 \003(\005\022\034\n\005dtype\030\003 \001(\0162\r.Schola.DType"
  "\032.\n\021BoxSpaceDimension\022\013\n\003low\030\001 \001(\002\022\014\n\004hi"
  "gh\030\002 \001(\002\"\035\n\rDiscreteSpace\022\014\n\004high\030\001 \001(\005\""
  "\"\n\022MultiDiscreteSpace\022\014\n\004high\030\001 \003(\005\"!\n\020M"
  "ultiBinarySpace\022\r\n\005shape\030\001 \001(\005\"\205\002\n\005Space"
  "\022%\n\tbox_space\030\001 \001(\0132\020.Schola.BoxSpaceH\000\022"
  "/\n\016discrete_space\030\002 \001(\0132\025.Schola.Discret"
  "eSpaceH\000\022:\n\024multi_discrete_space\030\003 \001(\0132\032"
  ".Schola.MultiDiscreteSpaceH\000\0226\n\022multi_bi"
  "nary_space\030\004 \001(\0132\030.Schola.MultiBinarySpa"
  "ceH\000\022\'\n\ndict_space\030\005 \001(\0132\021.Schola.DictSp"
  "aceH\000B\007\n\005space\"x\n\tDictSpace\022-\n\006spaces\030\001 "
  "\003(\0132\035.Schola.DictSpace.SpacesEntry\032<\n\013Sp"
  "acesEntry\022\013\n\003key\030\001 \001(\t\022\034\n\005value\030\002 \001(\0132\r."
  "Schola.Space:\0028\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Spaces_2eproto_deps[1] = {
  &::descriptor_table_DType_2eproto,
};
static ::_pbi::once_flag descriptor_table_Spaces_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Spaces_2eproto = {
    false, false, 704, descriptor_table_protodef_Spaces_2eproto,
    "Spaces.proto",
    &descriptor_table_Spaces_2eproto_once, descriptor_table_Spaces_2eproto_deps, 1, 8,
    schemas, file_default_instances, TableStruct_Spaces_2eproto::offsets,
    file_level_metadata_Spaces_2eproto, file_level_enum_descriptors_Spaces_2eproto,
    file_level_service_descriptors_Spaces_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Spaces_2eproto_getter() {
  return &descriptor_table_Spaces_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Spaces_2eproto(&descriptor_table_Spaces_2eproto);
namespace Schola {

// ===================================================================

class BoxSpace_BoxSpaceDimension::_Internal {
 public:
};

BoxSpace_BoxSpaceDimension::BoxSpace_BoxSpaceDimension(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.BoxSpace.BoxSpaceDimension)
}
BoxSpace_BoxSpaceDimension::BoxSpace_BoxSpaceDimension(const BoxSpace_BoxSpaceDimension& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BoxSpace_BoxSpaceDimension* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.low_){}
    , decltype(_impl_.high_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.low_, &from._impl_.low_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.high_) -
    reinterpret_cast<char*>(&_impl_.low_)) + sizeof(_impl_.high_));
  // @@protoc_insertion_point(copy_constructor:Schola.BoxSpace.BoxSpaceDimension)
}

inline void BoxSpace_BoxSpaceDimension::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.low_){0}
    , decltype(_impl_.high_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BoxSpace_BoxSpaceDimension::~BoxSpace_BoxSpaceDimension() {
  // @@protoc_insertion_point(destructor:Schola.BoxSpace.BoxSpaceDimension)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BoxSpace_BoxSpaceDimension::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BoxSpace_BoxSpaceDimension::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BoxSpace_BoxSpaceDimension::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.BoxSpace.BoxSpaceDimension)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.low_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.high_) -
      reinterpret_cast<char*>(&_impl_.low_)) + sizeof(_impl_.high_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BoxSpace_BoxSpaceDimension::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float low = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.low_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float high = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.high_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BoxSpace_BoxSpaceDimension::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.BoxSpace.BoxSpaceDimension)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float low = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_low = this->_internal_low();
  uint32_t raw_low;
  memcpy(&raw_low, &tmp_low, sizeof(tmp_low));
  if (raw_low != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_low(), target);
  }

  // float high = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_high = this->_internal_high();
  uint32_t raw_high;
  memcpy(&raw_high, &tmp_high, sizeof(tmp_high));
  if (raw_high != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_high(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.BoxSpace.BoxSpaceDimension)
  return target;
}

size_t BoxSpace_BoxSpaceDimension::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.BoxSpace.BoxSpaceDimension)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float low = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_low = this->_internal_low();
  uint32_t raw_low;
  memcpy(&raw_low, &tmp_low, sizeof(tmp_low));
  if (raw_low != 0) {
    total_size += 1 + 4;
  }

  // float high = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_high = this->_internal_high();
  uint32_t raw_high;
  memcpy(&raw_high, &tmp_high, sizeof(tmp_high));
  if (raw_high != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BoxSpace_BoxSpaceDimension::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BoxSpace_BoxSpaceDimension::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BoxSpace_BoxSpaceDimension::GetClassData() const { return &_class_data_; }


void BoxSpace_BoxSpaceDimension::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BoxSpace_BoxSpaceDimension*>(&to_msg);
  auto& from = static_cast<const BoxSpace_BoxSpaceDimension&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.BoxSpace.BoxSpaceDimension)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_low = from._internal_low();
  uint32_t raw_low;
  memcpy(&raw_low, &tmp_low, sizeof(tmp_low));
  if (raw_low != 0) {
    _this->_internal_set_low(from._internal_low());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_high = from._internal_high();
  uint32_t raw_high;
  memcpy(&raw_high, &tmp_high, sizeof(tmp_high));
  if (raw_high != 0) {
    _this->_internal_set_high(from._internal_high());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BoxSpace_BoxSpaceDimension::CopyFrom(const BoxSpace_BoxSpaceDimension& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.BoxSpace.BoxSpaceDimension)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoxSpace_BoxSpaceDimension::IsInitialized() const {
  return true;
}

void BoxSpace_BoxSpaceDimension::InternalSwap(BoxSpace_BoxSpaceDimension* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BoxSpace_BoxSpaceDimension, _impl_.high_)
      + sizeof(BoxSpace_BoxSpaceDimension::_impl_.high_)
      - PROTOBUF_FIELD_OFFSET(BoxSpace_BoxSpaceDimension, _impl_.low_)>(
          reinterpret_cast<char*>(&_impl_.low_),
          reinterpret_cast<char*>(&other->_impl_.low_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BoxSpace_BoxSpaceDimension::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[0]);
}

// ===================================================================

class BoxSpace::_Internal {
 public:
};

BoxSpace::BoxSpace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.BoxSpace)
}
BoxSpace::BoxSpace(const BoxSpace& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BoxSpace* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.dimensions_){from._impl_.dimensions_}
    , decltype(_impl_.shape_dimensions_){from._impl_.shape_dimensions_}
    , /*decltype(_impl_._shape_dimensions_cached_byte_size_)*/{0}
    , decltype(_impl_.dtype_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.dtype_ = from._impl_.dtype_;
  // @@protoc_insertion_point(copy_constructor:Schola.BoxSpace)
}

inline void BoxSpace::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.dimensions_){arena}
    , decltype(_impl_.shape_dimensions_){arena}
    , /*decltype(_impl_._shape_dimensions_cached_byte_size_)*/{0}
    , decltype(_impl_.dtype_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BoxSpace::~BoxSpace() {
  // @@protoc_insertion_point(destructor:Schola.BoxSpace)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BoxSpace::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.dimensions_.~RepeatedPtrField();
  _impl_.shape_dimensions_.~RepeatedField();
}

void BoxSpace::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BoxSpace::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.BoxSpace)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dimensions_.Clear();
  _impl_.shape_dimensions_.Clear();
  _impl_.dtype_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BoxSpace::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Schola.BoxSpace.BoxSpaceDimension dimensions = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_dimensions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated int32 shape_dimensions = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_shape_dimensions(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_shape_dimensions(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.DType dtype = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_dtype(static_cast<::Schola::DType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BoxSpace::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.BoxSpace)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Schola.BoxSpace.BoxSpaceDimension dimensions = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_dimensions_size()); i < n; i++) {
    const auto& repfield = this->_internal_dimensions(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated int32 shape_dimensions = 2;
  {
    int byte_size = _impl_._shape_dimensions_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_shape_dimensions(), byte_size, target);
    }
  }

  // .Schola.DType dtype = 3;
  if (this->_internal_dtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_dtype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.BoxSpace)
  return target;
}

size_t BoxSpace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.BoxSpace)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Schola.BoxSpace.BoxSpaceDimension dimensions = 1;
  total_size += 1UL * this->_internal_dimensions_size();
  for (const auto& msg : this->_impl_.dimensions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated int32 shape_dimensions = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.shape_dimensions_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._shape_dimensions_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .Schola.DType dtype = 3;
  if (this->_internal_dtype() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_dtype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BoxSpace::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BoxSpace::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BoxSpace::GetClassData() const { return &_class_data_; }


void BoxSpace::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BoxSpace*>(&to_msg);
  auto& from = static_cast<const BoxSpace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.BoxSpace)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.dimensions_.MergeFrom(from._impl_.dimensions_);
  _this->_impl_.shape_dimensions_.MergeFrom(from._impl_.shape_dimensions_);
  if (from._internal_dtype() != 0) {
    _this->_internal_set_dtype(from._internal_dtype());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BoxSpace::CopyFrom(const BoxSpace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.BoxSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoxSpace::IsInitialized() const {
  return true;
}

void BoxSpace::InternalSwap(BoxSpace* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.dimensions_.InternalSwap(&other->_impl_.dimensions_);
  _impl_.shape_dimensions_.InternalSwap(&other->_impl_.shape_dimensions_);
  swap(_impl_.dtype_, other->_impl_.dtype_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BoxSpace::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[1]);
}

// ===================================================================

class DiscreteSpace::_Internal {
 public:
};

DiscreteSpace::DiscreteSpace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.DiscreteSpace)
}
DiscreteSpace::DiscreteSpace(const DiscreteSpace& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DiscreteSpace* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.high_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.high_ = from._impl_.high_;
  // @@protoc_insertion_point(copy_constructor:Schola.DiscreteSpace)
}

inline void DiscreteSpace::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.high_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DiscreteSpace::~DiscreteSpace() {
  // @@protoc_insertion_point(destructor:Schola.DiscreteSpace)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DiscreteSpace::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DiscreteSpace::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DiscreteSpace::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.DiscreteSpace)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.high_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DiscreteSpace::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 high = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.high_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DiscreteSpace::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.DiscreteSpace)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 high = 1;
  if (this->_internal_high() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_high(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.DiscreteSpace)
  return target;
}

size_t DiscreteSpace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.DiscreteSpace)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 high = 1;
  if (this->_internal_high() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_high());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DiscreteSpace::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DiscreteSpace::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DiscreteSpace::GetClassData() const { return &_class_data_; }


void DiscreteSpace::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DiscreteSpace*>(&to_msg);
  auto& from = static_cast<const DiscreteSpace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.DiscreteSpace)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_high() != 0) {
    _this->_internal_set_high(from._internal_high());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DiscreteSpace::CopyFrom(const DiscreteSpace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.DiscreteSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiscreteSpace::IsInitialized() const {
  return true;
}

void DiscreteSpace::InternalSwap(DiscreteSpace* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.high_, other->_impl_.high_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DiscreteSpace::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[2]);
}

// ===================================================================

class MultiDiscreteSpace::_Internal {
 public:
};

MultiDiscreteSpace::MultiDiscreteSpace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.MultiDiscreteSpace)
}
MultiDiscreteSpace::MultiDiscreteSpace(const MultiDiscreteSpace& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MultiDiscreteSpace* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.high_){from._impl_.high_}
    , /*decltype(_impl_._high_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.MultiDiscreteSpace)
}

inline void MultiDiscreteSpace::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.high_){arena}
    , /*decltype(_impl_._high_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MultiDiscreteSpace::~MultiDiscreteSpace() {
  // @@protoc_insertion_point(destructor:Schola.MultiDiscreteSpace)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MultiDiscreteSpace::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.high_.~RepeatedField();
}

void MultiDiscreteSpace::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MultiDiscreteSpace::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.MultiDiscreteSpace)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.high_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MultiDiscreteSpace::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 high = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_high(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_high(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MultiDiscreteSpace::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.MultiDiscreteSpace)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 high = 1;
  {
    int byte_size = _impl_._high_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_high(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.MultiDiscreteSpace)
  return target;
}

size_t MultiDiscreteSpace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.MultiDiscreteSpace)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 high = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.high_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._high_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MultiDiscreteSpace::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MultiDiscreteSpace::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MultiDiscreteSpace::GetClassData() const { return &_class_data_; }


void MultiDiscreteSpace::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MultiDiscreteSpace*>(&to_msg);
  auto& from = static_cast<const MultiDiscreteSpace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.MultiDiscreteSpace)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.high_.MergeFrom(from._impl_.high_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MultiDiscreteSpace::CopyFrom(const MultiDiscreteSpace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.MultiDiscreteSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MultiDiscreteSpace::IsInitialized() const {
  return true;
}

void MultiDiscreteSpace::InternalSwap(MultiDiscreteSpace* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.high_.InternalSwap(&other->_impl_.high_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MultiDiscreteSpace::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[3]);
}

// ===================================================================

class MultiBinarySpace::_Internal {
 public:
};

MultiBinarySpace::MultiBinarySpace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.MultiBinarySpace)
}
MultiBinarySpace::MultiBinarySpace(const MultiBinarySpace& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MultiBinarySpace* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.shape_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.shape_ = from._impl_.shape_;
  // @@protoc_insertion_point(copy_constructor:Schola.MultiBinarySpace)
}

inline void MultiBinarySpace::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.shape_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MultiBinarySpace::~MultiBinarySpace() {
  // @@protoc_insertion_point(destructor:Schola.MultiBinarySpace)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MultiBinarySpace::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MultiBinarySpace::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MultiBinarySpace::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.MultiBinarySpace)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.shape_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MultiBinarySpace::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 shape = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.shape_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MultiBinarySpace::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.MultiBinarySpace)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 shape = 1;
  if (this->_internal_shape() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_shape(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.MultiBinarySpace)
  return target;
}

size_t MultiBinarySpace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.MultiBinarySpace)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 shape = 1;
  if (this->_internal_shape() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_shape());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MultiBinarySpace::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MultiBinarySpace::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MultiBinarySpace::GetClassData() const { return &_class_data_; }


void MultiBinarySpace::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MultiBinarySpace*>(&to_msg);
  auto& from = static_cast<const MultiBinarySpace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.MultiBinarySpace)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_shape() != 0) {
    _this->_internal_set_shape(from._internal_shape());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MultiBinarySpace::CopyFrom(const MultiBinarySpace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.MultiBinarySpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MultiBinarySpace::IsInitialized() const {
  return true;
}

void MultiBinarySpace::InternalSwap(MultiBinarySpace* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.shape_, other->_impl_.shape_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MultiBinarySpace::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[4]);
}

// ===================================================================

class Space::_Internal {
 public:
  static const ::Schola::BoxSpace& box_space(const Space* msg);
  static const ::Schola::DiscreteSpace& discrete_space(const Space* msg);
  static const ::Schola::MultiDiscreteSpace& multi_discrete_space(const Space* msg);
  static const ::Schola::MultiBinarySpace& multi_binary_space(const Space* msg);
  static const ::Schola::DictSpace& dict_space(const Space* msg);
};

const ::Schola::BoxSpace&
Space::_Internal::box_space(const Space* msg) {
  return *msg->_impl_.space_.box_space_;
}
const ::Schola::DiscreteSpace&
Space::_Internal::discrete_space(const Space* msg) {
  return *msg->_impl_.space_.discrete_space_;
}
const ::Schola::MultiDiscreteSpace&
Space::_Internal::multi_discrete_space(const Space* msg) {
  return *msg->_impl_.space_.multi_discrete_space_;
}
const ::Schola::MultiBinarySpace&
Space::_Internal::multi_binary_space(const Space* msg) {
  return *msg->_impl_.space_.multi_binary_space_;
}
const ::Schola::DictSpace&
Space::_Internal::dict_space(const Space* msg) {
  return *msg->_impl_.space_.dict_space_;
}
void Space::set_allocated_box_space(::Schola::BoxSpace* box_space) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_space();
  if (box_space) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(box_space);
    if (message_arena != submessage_arena) {
      box_space = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, box_space, submessage_arena);
    }
    set_has_box_space();
    _impl_.space_.box_space_ = box_space;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.Space.box_space)
}
void Space::set_allocated_discrete_space(::Schola::DiscreteSpace* discrete_space) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_space();
  if (discrete_space) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(discrete_space);
    if (message_arena != submessage_arena) {
      discrete_space = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, discrete_space, submessage_arena);
    }
    set_has_discrete_space();
    _impl_.space_.discrete_space_ = discrete_space;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.Space.discrete_space)
}
void Space::set_allocated_multi_discrete_space(::Schola::MultiDiscreteSpace* multi_discrete_space) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_space();
  if (multi_discrete_space) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(multi_discrete_space);
    if (message_arena != submessage_arena) {
      multi_discrete_space = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, multi_discrete_space, submessage_arena);
    }
    set_has_multi_discrete_space();
    _impl_.space_.multi_discrete_space_ = multi_discrete_space;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.Space.multi_discrete_space)
}
void Space::set_allocated_multi_binary_space(::Schola::MultiBinarySpace* multi_binary_space) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_space();
  if (multi_binary_space) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(multi_binary_space);
    if (message_arena != submessage_arena) {
      multi_binary_space = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, multi_binary_space, submessage_arena);
    }
    set_has_multi_binary_space();
    _impl_.space_.multi_binary_space_ = multi_binary_space;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.Space.multi_binary_space)
}
void Space::set_allocated_dict_space(::Schola::DictSpace* dict_space) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_space();
  if (dict_space) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(dict_space);
    if (message_arena != submessage_arena) {
      dict_space = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dict_space, submessage_arena);
    }
    set_has_dict_space();
    _impl_.space_.dict_space_ = dict_space;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.Space.dict_space)
}
Space::Space(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.Space)
}
Space::Space(const Space& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Space* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.space_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_space();
  switch (from.space_case()) {
    case kBoxSpace: {
      _this->_internal_mutable_box_space()->::Schola::BoxSpace::MergeFrom(
          from._internal_box_space());
      break;
    }
    case kDiscreteSpace: {
      _this->_internal_mutable_discrete_space()->::Schola::DiscreteSpace::MergeFrom(
          from._internal_discrete_space());
      break;
    }
    case kMultiDiscreteSpace: {
      _this->_internal_mutable_multi_discrete_space()->::Schola::MultiDiscreteSpace::MergeFrom(
          from._internal_multi_discrete_space());
      break;
    }
    case kMultiBinarySpace: {
      _this->_internal_mutable_multi_binary_space()->::Schola::MultiBinarySpace::MergeFrom(
          from._internal_multi_binary_space());
      break;
    }
    case kDictSpace: {
      _this->_internal_mutable_dict_space()->::Schola::DictSpace::MergeFrom(
          from._internal_dict_space());
      break;
    }
    case SPACE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Schola.Space)
}

inline void Space::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.space_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_space();
}

Space::~Space() {
  // @@protoc_insertion_point(destructor:Schola.Space)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Space::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_space()) {
    clear_space();
  }
}

void Space::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Space::clear_space() {
// @@protoc_insertion_point(one_of_clear_start:Schola.Space)
  switch (space_case()) {
    case kBoxSpace: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.space_.box_space_;
      }
      break;
    }
    case kDiscreteSpace: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.space_.discrete_space_;
      }
      break;
    }
    case kMultiDiscreteSpace: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.space_.multi_discrete_space_;
      }
      break;
    }
    case kMultiBinarySpace: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.space_.multi_binary_space_;
      }
      break;
    }
    case kDictSpace: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.space_.dict_space_;
      }
      break;
    }
    case SPACE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SPACE_NOT_SET;
}


void Space::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.Space)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_space();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Space::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Schola.BoxSpace box_space = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_box_space(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.DiscreteSpace discrete_space = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_discrete_space(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.MultiDiscreteSpace multi_discrete_space = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_multi_discrete_space(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.MultiBinarySpace multi_binary_space = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_multi_binary_space(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.DictSpace dict_space = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_dict_space(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Space::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.Space)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Schola.BoxSpace box_space = 1;
  if (_internal_has_box_space()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::box_space(this),
        _Internal::box_space(this).GetCachedSize(), target, stream);
  }

  // .Schola.DiscreteSpace discrete_space = 2;
  if (_internal_has_discrete_space()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::discrete_space(this),
        _Internal::discrete_space(this).GetCachedSize(), target, stream);
  }

  // .Schola.MultiDiscreteSpace multi_discrete_space = 3;
  if (_internal_has_multi_discrete_space()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::multi_discrete_space(this),
        _Internal::multi_discrete_space(this).GetCachedSize(), target, stream);
  }

  // .Schola.MultiBinarySpace multi_binary_space = 4;
  if (_internal_has_multi_binary_space()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::multi_binary_space(this),
        _Internal::multi_binary_space(this).GetCachedSize(), target, stream);
  }

  // .Schola.DictSpace dict_space = 5;
  if (_internal_has_dict_space()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::dict_space(this),
        _Internal::dict_space(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.Space)
  return target;
}

size_t Space::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.Space)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (space_case()) {
    // .Schola.BoxSpace box_space = 1;
    case kBoxSpace: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.space_.box_space_);
      break;
    }
    // .Schola.DiscreteSpace discrete_space = 2;
    case kDiscreteSpace: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.space_.discrete_space_);
      break;
    }
    // .Schola.MultiDiscreteSpace multi_discrete_space = 3;
    case kMultiDiscreteSpace: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.space_.multi_discrete_space_);
      break;
    }
    // .Schola.MultiBinarySpace multi_binary_space = 4;
    case kMultiBinarySpace: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.space_.multi_binary_space_);
      break;
    }
    // .Schola.DictSpace dict_space = 5;
    case kDictSpace: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.space_.dict_space_);
      break;
    }
    case SPACE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Space::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Space::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Space::GetClassData() const { return &_class_data_; }


void Space::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Space*>(&to_msg);
  auto& from = static_cast<const Space&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.Space)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.space_case()) {
    case kBoxSpace: {
      _this->_internal_mutable_box_space()->::Schola::BoxSpace::MergeFrom(
          from._internal_box_space());
      break;
    }
    case kDiscreteSpace: {
      _this->_internal_mutable_discrete_space()->::Schola::DiscreteSpace::MergeFrom(
          from._internal_discrete_space());
      break;
    }
    case kMultiDiscreteSpace: {
      _this->_internal_mutable_multi_discrete_space()->::Schola::MultiDiscreteSpace::MergeFrom(
          from._internal_multi_discrete_space());
      break;
    }
    case kMultiBinarySpace: {
      _this->_internal_mutable_multi_binary_space()->::Schola::MultiBinarySpace::MergeFrom(
          from._internal_multi_binary_space());
      break;
    }
    case kDictSpace: {
      _this->_internal_mutable_dict_space()->::Schola::DictSpace::MergeFrom(
          from._internal_dict_space());
      break;
    }
    case SPACE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Space::CopyFrom(const Space& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.Space)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Space::IsInitialized() const {
  return true;
}

void Space::InternalSwap(Space* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.space_, other->_impl_.space_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Space::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[5]);
}

// ===================================================================

DictSpace_SpacesEntry_DoNotUse::DictSpace_SpacesEntry_DoNotUse() {}
DictSpace_SpacesEntry_DoNotUse::DictSpace_SpacesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void DictSpace_SpacesEntry_DoNotUse::MergeFrom(const DictSpace_SpacesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata DictSpace_SpacesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[6]);
}

// ===================================================================

class DictSpace::_Internal {
 public:
};

DictSpace::DictSpace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &DictSpace::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.DictSpace)
}
DictSpace::DictSpace(const DictSpace& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DictSpace* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.spaces_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.spaces_.MergeFrom(from._impl_.spaces_);
  // @@protoc_insertion_point(copy_constructor:Schola.DictSpace)
}

inline void DictSpace::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.spaces_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DictSpace::~DictSpace() {
  // @@protoc_insertion_point(destructor:Schola.DictSpace)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void DictSpace::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.spaces_.Destruct();
  _impl_.spaces_.~MapField();
}

void DictSpace::ArenaDtor(void* object) {
  DictSpace* _this = reinterpret_cast< DictSpace* >(object);
  _this->_impl_.spaces_.Destruct();
}
void DictSpace::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DictSpace::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.DictSpace)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.spaces_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DictSpace::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .Schola.Space> spaces = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.spaces_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DictSpace::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.DictSpace)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .Schola.Space> spaces = 1;
  if (!this->_internal_spaces().empty()) {
    using MapType = ::_pb::Map<std::string, ::Schola::Space>;
    using WireHelper = DictSpace_SpacesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_spaces();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.DictSpace.SpacesEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.DictSpace)
  return target;
}

size_t DictSpace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.DictSpace)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .Schola.Space> spaces = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_spaces_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::Space >::const_iterator
      it = this->_internal_spaces().begin();
      it != this->_internal_spaces().end(); ++it) {
    total_size += DictSpace_SpacesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DictSpace::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DictSpace::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DictSpace::GetClassData() const { return &_class_data_; }


void DictSpace::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DictSpace*>(&to_msg);
  auto& from = static_cast<const DictSpace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.DictSpace)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.spaces_.MergeFrom(from._impl_.spaces_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DictSpace::CopyFrom(const DictSpace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.DictSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DictSpace::IsInitialized() const {
  return true;
}

void DictSpace::InternalSwap(DictSpace* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.spaces_.InternalSwap(&other->_impl_.spaces_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DictSpace::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Spaces_2eproto_getter, &descriptor_table_Spaces_2eproto_once,
      file_level_metadata_Spaces_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Schola::BoxSpace_BoxSpaceDimension*
Arena::CreateMaybeMessage< ::Schola::BoxSpace_BoxSpaceDimension >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::BoxSpace_BoxSpaceDimension >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::BoxSpace*
Arena::CreateMaybeMessage< ::Schola::BoxSpace >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::BoxSpace >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::DiscreteSpace*
Arena::CreateMaybeMessage< ::Schola::DiscreteSpace >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::DiscreteSpace >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::MultiDiscreteSpace*
Arena::CreateMaybeMessage< ::Schola::MultiDiscreteSpace >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::MultiDiscreteSpace >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::MultiBinarySpace*
Arena::CreateMaybeMessage< ::Schola::MultiBinarySpace >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::MultiBinarySpace >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::Space*
Arena::CreateMaybeMessage< ::Schola::Space >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::Space >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::DictSpace_SpacesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::DictSpace_SpacesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::DictSpace_SpacesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::DictSpace*
Arena::CreateMaybeMessage< ::Schola::DictSpace >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::DictSpace >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
