// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: State.proto

#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#include "State.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Schola {
PROTOBUF_CONSTEXPR AgentState_InfoEntry_DoNotUse::AgentState_InfoEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct AgentState_InfoEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentState_InfoEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentState_InfoEntry_DoNotUseDefaultTypeInternal() {}
  union {
    AgentState_InfoEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentState_InfoEntry_DoNotUseDefaultTypeInternal _AgentState_InfoEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR AgentState::AgentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.info_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.observations_)*/nullptr
  , /*decltype(_impl_.reward_)*/0
  , /*decltype(_impl_.terminated_)*/false
  , /*decltype(_impl_.truncated_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentStateDefaultTypeInternal() {}
  union {
    AgentState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentStateDefaultTypeInternal _AgentState_default_instance_;
PROTOBUF_CONSTEXPR EnvironmentState_AgentStatesEntry_DoNotUse::EnvironmentState_AgentStatesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct EnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    EnvironmentState_AgentStatesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal _EnvironmentState_AgentStatesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR EnvironmentState::EnvironmentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.agent_states_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EnvironmentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentStateDefaultTypeInternal() {}
  union {
    EnvironmentState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentStateDefaultTypeInternal _EnvironmentState_default_instance_;
PROTOBUF_CONSTEXPR TrainingState::TrainingState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.environment_states_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TrainingStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrainingStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrainingStateDefaultTypeInternal() {}
  union {
    TrainingState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrainingStateDefaultTypeInternal _TrainingState_default_instance_;
PROTOBUF_CONSTEXPR InitialAgentState_InfoEntry_DoNotUse::InitialAgentState_InfoEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct InitialAgentState_InfoEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitialAgentState_InfoEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitialAgentState_InfoEntry_DoNotUseDefaultTypeInternal() {}
  union {
    InitialAgentState_InfoEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitialAgentState_InfoEntry_DoNotUseDefaultTypeInternal _InitialAgentState_InfoEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR InitialAgentState::InitialAgentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.info_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.observations_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InitialAgentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitialAgentStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitialAgentStateDefaultTypeInternal() {}
  union {
    InitialAgentState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitialAgentStateDefaultTypeInternal _InitialAgentState_default_instance_;
PROTOBUF_CONSTEXPR InitialEnvironmentState_AgentStatesEntry_DoNotUse::InitialEnvironmentState_AgentStatesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct InitialEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitialEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitialEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    InitialEnvironmentState_AgentStatesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitialEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal _InitialEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR InitialEnvironmentState::InitialEnvironmentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.agent_states_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InitialEnvironmentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitialEnvironmentStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitialEnvironmentStateDefaultTypeInternal() {}
  union {
    InitialEnvironmentState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitialEnvironmentStateDefaultTypeInternal _InitialEnvironmentState_default_instance_;
PROTOBUF_CONSTEXPR InitialState_EnvironmentStatesEntry_DoNotUse::InitialState_EnvironmentStatesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct InitialState_EnvironmentStatesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitialState_EnvironmentStatesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitialState_EnvironmentStatesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    InitialState_EnvironmentStatesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitialState_EnvironmentStatesEntry_DoNotUseDefaultTypeInternal _InitialState_EnvironmentStatesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR InitialState::InitialState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.environment_states_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InitialStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InitialStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InitialStateDefaultTypeInternal() {}
  union {
    InitialState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitialStateDefaultTypeInternal _InitialState_default_instance_;
PROTOBUF_CONSTEXPR State::State(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.optional_training_state_)*/{}
  , /*decltype(_impl_.optional_initial_state_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct StateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StateDefaultTypeInternal() {}
  union {
    State _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StateDefaultTypeInternal _State_default_instance_;
}  // namespace Schola
static ::_pb::Metadata file_level_metadata_State_2eproto[12];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_State_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_State_2eproto = nullptr;

const uint32_t TableStruct_State_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState_InfoEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState_InfoEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState_InfoEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState_InfoEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState, _impl_.observations_),
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState, _impl_.reward_),
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState, _impl_.terminated_),
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState, _impl_.truncated_),
  PROTOBUF_FIELD_OFFSET(::Schola::AgentState, _impl_.info_),
  PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentState_AgentStatesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentState_AgentStatesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentState_AgentStatesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentState_AgentStatesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::EnvironmentState, _impl_.agent_states_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::TrainingState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::TrainingState, _impl_.environment_states_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialAgentState_InfoEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialAgentState_InfoEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialAgentState_InfoEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialAgentState_InfoEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialAgentState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialAgentState, _impl_.observations_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialAgentState, _impl_.info_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialEnvironmentState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialEnvironmentState, _impl_.agent_states_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialState_EnvironmentStatesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialState_EnvironmentStatesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialState_EnvironmentStatesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::InitialState_EnvironmentStatesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::InitialState, _impl_.environment_states_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::State, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Schola::State, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Schola::State, _impl_.optional_training_state_),
  PROTOBUF_FIELD_OFFSET(::Schola::State, _impl_.optional_initial_state_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::Schola::AgentState_InfoEntry_DoNotUse)},
  { 10, -1, -1, sizeof(::Schola::AgentState)},
  { 21, 29, -1, sizeof(::Schola::EnvironmentState_AgentStatesEntry_DoNotUse)},
  { 31, -1, -1, sizeof(::Schola::EnvironmentState)},
  { 38, -1, -1, sizeof(::Schola::TrainingState)},
  { 45, 53, -1, sizeof(::Schola::InitialAgentState_InfoEntry_DoNotUse)},
  { 55, -1, -1, sizeof(::Schola::InitialAgentState)},
  { 63, 71, -1, sizeof(::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse)},
  { 73, -1, -1, sizeof(::Schola::InitialEnvironmentState)},
  { 80, 88, -1, sizeof(::Schola::InitialState_EnvironmentStatesEntry_DoNotUse)},
  { 90, -1, -1, sizeof(::Schola::InitialState)},
  { 97, -1, -1, sizeof(::Schola::State)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Schola::_AgentState_InfoEntry_DoNotUse_default_instance_._instance,
  &::Schola::_AgentState_default_instance_._instance,
  &::Schola::_EnvironmentState_AgentStatesEntry_DoNotUse_default_instance_._instance,
  &::Schola::_EnvironmentState_default_instance_._instance,
  &::Schola::_TrainingState_default_instance_._instance,
  &::Schola::_InitialAgentState_InfoEntry_DoNotUse_default_instance_._instance,
  &::Schola::_InitialAgentState_default_instance_._instance,
  &::Schola::_InitialEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_._instance,
  &::Schola::_InitialEnvironmentState_default_instance_._instance,
  &::Schola::_InitialState_EnvironmentStatesEntry_DoNotUse_default_instance_._instance,
  &::Schola::_InitialState_default_instance_._instance,
  &::Schola::_State_default_instance_._instance,
};

const char descriptor_table_protodef_State_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013State.proto\022\006Schola\032\014Points.proto\"\301\001\n\n"
  "AgentState\022#\n\014observations\030\001 \001(\0132\r.Schol"
  "a.Point\022\016\n\006reward\030\002 \001(\002\022\022\n\nterminated\030\003 "
  "\001(\010\022\021\n\ttruncated\030\004 \001(\010\022*\n\004info\030\005 \003(\0132\034.S"
  "chola.AgentState.InfoEntry\032+\n\tInfoEntry\022"
  "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\233\001\n\020Envi"
  "ronmentState\022\?\n\014agent_states\030\001 \003(\0132).Sch"
  "ola.EnvironmentState.AgentStatesEntry\032F\n"
  "\020AgentStatesEntry\022\013\n\003key\030\001 \001(\t\022!\n\005value\030"
  "\002 \001(\0132\022.Schola.AgentState:\0028\001\"E\n\rTrainin"
  "gState\0224\n\022environment_states\030\001 \003(\0132\030.Sch"
  "ola.EnvironmentState\"\230\001\n\021InitialAgentSta"
  "te\022#\n\014observations\030\001 \001(\0132\r.Schola.Point\022"
  "1\n\004info\030\004 \003(\0132#.Schola.InitialAgentState"
  ".InfoEntry\032+\n\tInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005"
  "value\030\002 \001(\t:\0028\001\"\260\001\n\027InitialEnvironmentSt"
  "ate\022F\n\014agent_states\030\001 \003(\01320.Schola.Initi"
  "alEnvironmentState.AgentStatesEntry\032M\n\020A"
  "gentStatesEntry\022\013\n\003key\030\001 \001(\t\022(\n\005value\030\002 "
  "\001(\0132\031.Schola.InitialAgentState:\0028\001\"\262\001\n\014I"
  "nitialState\022G\n\022environment_states\030\001 \003(\0132"
  "+.Schola.InitialState.EnvironmentStatesE"
  "ntry\032Y\n\026EnvironmentStatesEntry\022\013\n\003key\030\001 "
  "\001(\005\022.\n\005value\030\002 \001(\0132\037.Schola.InitialEnvir"
  "onmentState:\0028\001\"\234\001\n\005State\022/\n\016training_st"
  "ate\030\001 \001(\0132\025.Schola.TrainingStateH\000\022-\n\rin"
  "itial_state\030\002 \001(\0132\024.Schola.InitialStateH"
  "\001B\031\n\027optional_training_stateB\030\n\026optional"
  "_initial_stateb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_State_2eproto_deps[1] = {
  &::descriptor_table_Points_2eproto,
};
static ::_pbi::once_flag descriptor_table_State_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_State_2eproto = {
    false, false, 1142, descriptor_table_protodef_State_2eproto,
    "State.proto",
    &descriptor_table_State_2eproto_once, descriptor_table_State_2eproto_deps, 1, 12,
    schemas, file_default_instances, TableStruct_State_2eproto::offsets,
    file_level_metadata_State_2eproto, file_level_enum_descriptors_State_2eproto,
    file_level_service_descriptors_State_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_State_2eproto_getter() {
  return &descriptor_table_State_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_State_2eproto(&descriptor_table_State_2eproto);
namespace Schola {

// ===================================================================

AgentState_InfoEntry_DoNotUse::AgentState_InfoEntry_DoNotUse() {}
AgentState_InfoEntry_DoNotUse::AgentState_InfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void AgentState_InfoEntry_DoNotUse::MergeFrom(const AgentState_InfoEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata AgentState_InfoEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[0]);
}

// ===================================================================

class AgentState::_Internal {
 public:
  static const ::Schola::Point& observations(const AgentState* msg);
};

const ::Schola::Point&
AgentState::_Internal::observations(const AgentState* msg) {
  return *msg->_impl_.observations_;
}
void AgentState::clear_observations() {
  if (GetArenaForAllocation() == nullptr && _impl_.observations_ != nullptr) {
    delete _impl_.observations_;
  }
  _impl_.observations_ = nullptr;
}
AgentState::AgentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &AgentState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.AgentState)
}
AgentState::AgentState(const AgentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AgentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.info_)*/{}
    , decltype(_impl_.observations_){nullptr}
    , decltype(_impl_.reward_){}
    , decltype(_impl_.terminated_){}
    , decltype(_impl_.truncated_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.info_.MergeFrom(from._impl_.info_);
  if (from._internal_has_observations()) {
    _this->_impl_.observations_ = new ::Schola::Point(*from._impl_.observations_);
  }
  ::memcpy(&_impl_.reward_, &from._impl_.reward_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.truncated_) -
    reinterpret_cast<char*>(&_impl_.reward_)) + sizeof(_impl_.truncated_));
  // @@protoc_insertion_point(copy_constructor:Schola.AgentState)
}

inline void AgentState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.info_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.observations_){nullptr}
    , decltype(_impl_.reward_){0}
    , decltype(_impl_.terminated_){false}
    , decltype(_impl_.truncated_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AgentState::~AgentState() {
  // @@protoc_insertion_point(destructor:Schola.AgentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void AgentState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.info_.Destruct();
  _impl_.info_.~MapField();
  if (this != internal_default_instance()) delete _impl_.observations_;
}

void AgentState::ArenaDtor(void* object) {
  AgentState* _this = reinterpret_cast< AgentState* >(object);
  _this->_impl_.info_.Destruct();
}
void AgentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgentState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.AgentState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.info_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.observations_ != nullptr) {
    delete _impl_.observations_;
  }
  _impl_.observations_ = nullptr;
  ::memset(&_impl_.reward_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.truncated_) -
      reinterpret_cast<char*>(&_impl_.reward_)) + sizeof(_impl_.truncated_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Schola.Point observations = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_observations(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float reward = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.reward_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool terminated = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.terminated_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool truncated = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.truncated_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, string> info = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.info_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AgentState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.AgentState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Schola.Point observations = 1;
  if (this->_internal_has_observations()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::observations(this),
        _Internal::observations(this).GetCachedSize(), target, stream);
  }

  // float reward = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_reward = this->_internal_reward();
  uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_reward(), target);
  }

  // bool terminated = 3;
  if (this->_internal_terminated() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_terminated(), target);
  }

  // bool truncated = 4;
  if (this->_internal_truncated() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_truncated(), target);
  }

  // map<string, string> info = 5;
  if (!this->_internal_info().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = AgentState_InfoEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_info();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.AgentState.InfoEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.AgentState.InfoEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.AgentState)
  return target;
}

size_t AgentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.AgentState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> info = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_info_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_info().begin();
      it != this->_internal_info().end(); ++it) {
    total_size += AgentState_InfoEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .Schola.Point observations = 1;
  if (this->_internal_has_observations()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.observations_);
  }

  // float reward = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_reward = this->_internal_reward();
  uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    total_size += 1 + 4;
  }

  // bool terminated = 3;
  if (this->_internal_terminated() != 0) {
    total_size += 1 + 1;
  }

  // bool truncated = 4;
  if (this->_internal_truncated() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgentState::GetClassData() const { return &_class_data_; }


void AgentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgentState*>(&to_msg);
  auto& from = static_cast<const AgentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.AgentState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.info_.MergeFrom(from._impl_.info_);
  if (from._internal_has_observations()) {
    _this->_internal_mutable_observations()->::Schola::Point::MergeFrom(
        from._internal_observations());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_reward = from._internal_reward();
  uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    _this->_internal_set_reward(from._internal_reward());
  }
  if (from._internal_terminated() != 0) {
    _this->_internal_set_terminated(from._internal_terminated());
  }
  if (from._internal_truncated() != 0) {
    _this->_internal_set_truncated(from._internal_truncated());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgentState::CopyFrom(const AgentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.AgentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgentState::IsInitialized() const {
  return true;
}

void AgentState::InternalSwap(AgentState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.info_.InternalSwap(&other->_impl_.info_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AgentState, _impl_.truncated_)
      + sizeof(AgentState::_impl_.truncated_)
      - PROTOBUF_FIELD_OFFSET(AgentState, _impl_.observations_)>(
          reinterpret_cast<char*>(&_impl_.observations_),
          reinterpret_cast<char*>(&other->_impl_.observations_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AgentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[1]);
}

// ===================================================================

EnvironmentState_AgentStatesEntry_DoNotUse::EnvironmentState_AgentStatesEntry_DoNotUse() {}
EnvironmentState_AgentStatesEntry_DoNotUse::EnvironmentState_AgentStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void EnvironmentState_AgentStatesEntry_DoNotUse::MergeFrom(const EnvironmentState_AgentStatesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata EnvironmentState_AgentStatesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[2]);
}

// ===================================================================

class EnvironmentState::_Internal {
 public:
};

EnvironmentState::EnvironmentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &EnvironmentState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.EnvironmentState)
}
EnvironmentState::EnvironmentState(const EnvironmentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EnvironmentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.agent_states_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.agent_states_.MergeFrom(from._impl_.agent_states_);
  // @@protoc_insertion_point(copy_constructor:Schola.EnvironmentState)
}

inline void EnvironmentState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.agent_states_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

EnvironmentState::~EnvironmentState() {
  // @@protoc_insertion_point(destructor:Schola.EnvironmentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void EnvironmentState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.agent_states_.Destruct();
  _impl_.agent_states_.~MapField();
}

void EnvironmentState::ArenaDtor(void* object) {
  EnvironmentState* _this = reinterpret_cast< EnvironmentState* >(object);
  _this->_impl_.agent_states_.Destruct();
}
void EnvironmentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EnvironmentState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.EnvironmentState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agent_states_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EnvironmentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .Schola.AgentState> agent_states = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.agent_states_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EnvironmentState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.EnvironmentState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .Schola.AgentState> agent_states = 1;
  if (!this->_internal_agent_states().empty()) {
    using MapType = ::_pb::Map<std::string, ::Schola::AgentState>;
    using WireHelper = EnvironmentState_AgentStatesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_agent_states();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.EnvironmentState.AgentStatesEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.EnvironmentState)
  return target;
}

size_t EnvironmentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.EnvironmentState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .Schola.AgentState> agent_states = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_agent_states_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >::const_iterator
      it = this->_internal_agent_states().begin();
      it != this->_internal_agent_states().end(); ++it) {
    total_size += EnvironmentState_AgentStatesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EnvironmentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EnvironmentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EnvironmentState::GetClassData() const { return &_class_data_; }


void EnvironmentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EnvironmentState*>(&to_msg);
  auto& from = static_cast<const EnvironmentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.EnvironmentState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.agent_states_.MergeFrom(from._impl_.agent_states_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EnvironmentState::CopyFrom(const EnvironmentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.EnvironmentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnvironmentState::IsInitialized() const {
  return true;
}

void EnvironmentState::InternalSwap(EnvironmentState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.agent_states_.InternalSwap(&other->_impl_.agent_states_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EnvironmentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[3]);
}

// ===================================================================

class TrainingState::_Internal {
 public:
};

TrainingState::TrainingState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.TrainingState)
}
TrainingState::TrainingState(const TrainingState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TrainingState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.environment_states_){from._impl_.environment_states_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.TrainingState)
}

inline void TrainingState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.environment_states_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TrainingState::~TrainingState() {
  // @@protoc_insertion_point(destructor:Schola.TrainingState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TrainingState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.environment_states_.~RepeatedPtrField();
}

void TrainingState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TrainingState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.TrainingState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.environment_states_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TrainingState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Schola.EnvironmentState environment_states = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_environment_states(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TrainingState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.TrainingState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Schola.EnvironmentState environment_states = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_environment_states_size()); i < n; i++) {
    const auto& repfield = this->_internal_environment_states(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.TrainingState)
  return target;
}

size_t TrainingState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.TrainingState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Schola.EnvironmentState environment_states = 1;
  total_size += 1UL * this->_internal_environment_states_size();
  for (const auto& msg : this->_impl_.environment_states_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TrainingState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TrainingState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TrainingState::GetClassData() const { return &_class_data_; }


void TrainingState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TrainingState*>(&to_msg);
  auto& from = static_cast<const TrainingState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.TrainingState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.environment_states_.MergeFrom(from._impl_.environment_states_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TrainingState::CopyFrom(const TrainingState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.TrainingState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrainingState::IsInitialized() const {
  return true;
}

void TrainingState::InternalSwap(TrainingState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.environment_states_.InternalSwap(&other->_impl_.environment_states_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TrainingState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[4]);
}

// ===================================================================

InitialAgentState_InfoEntry_DoNotUse::InitialAgentState_InfoEntry_DoNotUse() {}
InitialAgentState_InfoEntry_DoNotUse::InitialAgentState_InfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void InitialAgentState_InfoEntry_DoNotUse::MergeFrom(const InitialAgentState_InfoEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata InitialAgentState_InfoEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[5]);
}

// ===================================================================

class InitialAgentState::_Internal {
 public:
  static const ::Schola::Point& observations(const InitialAgentState* msg);
};

const ::Schola::Point&
InitialAgentState::_Internal::observations(const InitialAgentState* msg) {
  return *msg->_impl_.observations_;
}
void InitialAgentState::clear_observations() {
  if (GetArenaForAllocation() == nullptr && _impl_.observations_ != nullptr) {
    delete _impl_.observations_;
  }
  _impl_.observations_ = nullptr;
}
InitialAgentState::InitialAgentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &InitialAgentState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.InitialAgentState)
}
InitialAgentState::InitialAgentState(const InitialAgentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InitialAgentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.info_)*/{}
    , decltype(_impl_.observations_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.info_.MergeFrom(from._impl_.info_);
  if (from._internal_has_observations()) {
    _this->_impl_.observations_ = new ::Schola::Point(*from._impl_.observations_);
  }
  // @@protoc_insertion_point(copy_constructor:Schola.InitialAgentState)
}

inline void InitialAgentState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.info_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.observations_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InitialAgentState::~InitialAgentState() {
  // @@protoc_insertion_point(destructor:Schola.InitialAgentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void InitialAgentState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.info_.Destruct();
  _impl_.info_.~MapField();
  if (this != internal_default_instance()) delete _impl_.observations_;
}

void InitialAgentState::ArenaDtor(void* object) {
  InitialAgentState* _this = reinterpret_cast< InitialAgentState* >(object);
  _this->_impl_.info_.Destruct();
}
void InitialAgentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InitialAgentState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.InitialAgentState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.info_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.observations_ != nullptr) {
    delete _impl_.observations_;
  }
  _impl_.observations_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InitialAgentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Schola.Point observations = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_observations(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, string> info = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.info_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InitialAgentState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.InitialAgentState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Schola.Point observations = 1;
  if (this->_internal_has_observations()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::observations(this),
        _Internal::observations(this).GetCachedSize(), target, stream);
  }

  // map<string, string> info = 4;
  if (!this->_internal_info().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = InitialAgentState_InfoEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_info();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.InitialAgentState.InfoEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.InitialAgentState.InfoEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(4, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(4, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.InitialAgentState)
  return target;
}

size_t InitialAgentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.InitialAgentState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> info = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_info_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_info().begin();
      it != this->_internal_info().end(); ++it) {
    total_size += InitialAgentState_InfoEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .Schola.Point observations = 1;
  if (this->_internal_has_observations()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.observations_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InitialAgentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InitialAgentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InitialAgentState::GetClassData() const { return &_class_data_; }


void InitialAgentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InitialAgentState*>(&to_msg);
  auto& from = static_cast<const InitialAgentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.InitialAgentState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.info_.MergeFrom(from._impl_.info_);
  if (from._internal_has_observations()) {
    _this->_internal_mutable_observations()->::Schola::Point::MergeFrom(
        from._internal_observations());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InitialAgentState::CopyFrom(const InitialAgentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.InitialAgentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InitialAgentState::IsInitialized() const {
  return true;
}

void InitialAgentState::InternalSwap(InitialAgentState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.info_.InternalSwap(&other->_impl_.info_);
  swap(_impl_.observations_, other->_impl_.observations_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InitialAgentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[6]);
}

// ===================================================================

InitialEnvironmentState_AgentStatesEntry_DoNotUse::InitialEnvironmentState_AgentStatesEntry_DoNotUse() {}
InitialEnvironmentState_AgentStatesEntry_DoNotUse::InitialEnvironmentState_AgentStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void InitialEnvironmentState_AgentStatesEntry_DoNotUse::MergeFrom(const InitialEnvironmentState_AgentStatesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata InitialEnvironmentState_AgentStatesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[7]);
}

// ===================================================================

class InitialEnvironmentState::_Internal {
 public:
};

InitialEnvironmentState::InitialEnvironmentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &InitialEnvironmentState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.InitialEnvironmentState)
}
InitialEnvironmentState::InitialEnvironmentState(const InitialEnvironmentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InitialEnvironmentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.agent_states_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.agent_states_.MergeFrom(from._impl_.agent_states_);
  // @@protoc_insertion_point(copy_constructor:Schola.InitialEnvironmentState)
}

inline void InitialEnvironmentState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.agent_states_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InitialEnvironmentState::~InitialEnvironmentState() {
  // @@protoc_insertion_point(destructor:Schola.InitialEnvironmentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void InitialEnvironmentState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.agent_states_.Destruct();
  _impl_.agent_states_.~MapField();
}

void InitialEnvironmentState::ArenaDtor(void* object) {
  InitialEnvironmentState* _this = reinterpret_cast< InitialEnvironmentState* >(object);
  _this->_impl_.agent_states_.Destruct();
}
void InitialEnvironmentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InitialEnvironmentState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.InitialEnvironmentState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agent_states_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InitialEnvironmentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .Schola.InitialAgentState> agent_states = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.agent_states_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InitialEnvironmentState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.InitialEnvironmentState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .Schola.InitialAgentState> agent_states = 1;
  if (!this->_internal_agent_states().empty()) {
    using MapType = ::_pb::Map<std::string, ::Schola::InitialAgentState>;
    using WireHelper = InitialEnvironmentState_AgentStatesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_agent_states();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.InitialEnvironmentState.AgentStatesEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.InitialEnvironmentState)
  return target;
}

size_t InitialEnvironmentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.InitialEnvironmentState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .Schola.InitialAgentState> agent_states = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_agent_states_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >::const_iterator
      it = this->_internal_agent_states().begin();
      it != this->_internal_agent_states().end(); ++it) {
    total_size += InitialEnvironmentState_AgentStatesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InitialEnvironmentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InitialEnvironmentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InitialEnvironmentState::GetClassData() const { return &_class_data_; }


void InitialEnvironmentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InitialEnvironmentState*>(&to_msg);
  auto& from = static_cast<const InitialEnvironmentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.InitialEnvironmentState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.agent_states_.MergeFrom(from._impl_.agent_states_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InitialEnvironmentState::CopyFrom(const InitialEnvironmentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.InitialEnvironmentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InitialEnvironmentState::IsInitialized() const {
  return true;
}

void InitialEnvironmentState::InternalSwap(InitialEnvironmentState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.agent_states_.InternalSwap(&other->_impl_.agent_states_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InitialEnvironmentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[8]);
}

// ===================================================================

InitialState_EnvironmentStatesEntry_DoNotUse::InitialState_EnvironmentStatesEntry_DoNotUse() {}
InitialState_EnvironmentStatesEntry_DoNotUse::InitialState_EnvironmentStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void InitialState_EnvironmentStatesEntry_DoNotUse::MergeFrom(const InitialState_EnvironmentStatesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata InitialState_EnvironmentStatesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[9]);
}

// ===================================================================

class InitialState::_Internal {
 public:
};

InitialState::InitialState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &InitialState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.InitialState)
}
InitialState::InitialState(const InitialState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InitialState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.environment_states_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.environment_states_.MergeFrom(from._impl_.environment_states_);
  // @@protoc_insertion_point(copy_constructor:Schola.InitialState)
}

inline void InitialState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.environment_states_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InitialState::~InitialState() {
  // @@protoc_insertion_point(destructor:Schola.InitialState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void InitialState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.environment_states_.Destruct();
  _impl_.environment_states_.~MapField();
}

void InitialState::ArenaDtor(void* object) {
  InitialState* _this = reinterpret_cast< InitialState* >(object);
  _this->_impl_.environment_states_.Destruct();
}
void InitialState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InitialState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.InitialState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.environment_states_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InitialState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<int32, .Schola.InitialEnvironmentState> environment_states = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.environment_states_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InitialState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.InitialState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, .Schola.InitialEnvironmentState> environment_states = 1;
  if (!this->_internal_environment_states().empty()) {
    using MapType = ::_pb::Map<int32_t, ::Schola::InitialEnvironmentState>;
    using WireHelper = InitialState_EnvironmentStatesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_environment_states();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.InitialState)
  return target;
}

size_t InitialState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.InitialState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .Schola.InitialEnvironmentState> environment_states = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_environment_states_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >::const_iterator
      it = this->_internal_environment_states().begin();
      it != this->_internal_environment_states().end(); ++it) {
    total_size += InitialState_EnvironmentStatesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InitialState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InitialState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InitialState::GetClassData() const { return &_class_data_; }


void InitialState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InitialState*>(&to_msg);
  auto& from = static_cast<const InitialState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.InitialState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.environment_states_.MergeFrom(from._impl_.environment_states_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InitialState::CopyFrom(const InitialState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.InitialState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InitialState::IsInitialized() const {
  return true;
}

void InitialState::InternalSwap(InitialState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.environment_states_.InternalSwap(&other->_impl_.environment_states_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InitialState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[10]);
}

// ===================================================================

class State::_Internal {
 public:
  static const ::Schola::TrainingState& training_state(const State* msg);
  static const ::Schola::InitialState& initial_state(const State* msg);
};

const ::Schola::TrainingState&
State::_Internal::training_state(const State* msg) {
  return *msg->_impl_.optional_training_state_.training_state_;
}
const ::Schola::InitialState&
State::_Internal::initial_state(const State* msg) {
  return *msg->_impl_.optional_initial_state_.initial_state_;
}
void State::set_allocated_training_state(::Schola::TrainingState* training_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_optional_training_state();
  if (training_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(training_state);
    if (message_arena != submessage_arena) {
      training_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, training_state, submessage_arena);
    }
    set_has_training_state();
    _impl_.optional_training_state_.training_state_ = training_state;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.State.training_state)
}
void State::set_allocated_initial_state(::Schola::InitialState* initial_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_optional_initial_state();
  if (initial_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(initial_state);
    if (message_arena != submessage_arena) {
      initial_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, initial_state, submessage_arena);
    }
    set_has_initial_state();
    _impl_.optional_initial_state_.initial_state_ = initial_state;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.State.initial_state)
}
State::State(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.State)
}
State::State(const State& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  State* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.optional_training_state_){}
    , decltype(_impl_.optional_initial_state_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_optional_training_state();
  switch (from.optional_training_state_case()) {
    case kTrainingState: {
      _this->_internal_mutable_training_state()->::Schola::TrainingState::MergeFrom(
          from._internal_training_state());
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  clear_has_optional_initial_state();
  switch (from.optional_initial_state_case()) {
    case kInitialState: {
      _this->_internal_mutable_initial_state()->::Schola::InitialState::MergeFrom(
          from._internal_initial_state());
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Schola.State)
}

inline void State::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.optional_training_state_){}
    , decltype(_impl_.optional_initial_state_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_optional_training_state();
  clear_has_optional_initial_state();
}

State::~State() {
  // @@protoc_insertion_point(destructor:Schola.State)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void State::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_optional_training_state()) {
    clear_optional_training_state();
  }
  if (has_optional_initial_state()) {
    clear_optional_initial_state();
  }
}

void State::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void State::clear_optional_training_state() {
// @@protoc_insertion_point(one_of_clear_start:Schola.State)
  switch (optional_training_state_case()) {
    case kTrainingState: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.optional_training_state_.training_state_;
      }
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = OPTIONAL_TRAINING_STATE_NOT_SET;
}

void State::clear_optional_initial_state() {
// @@protoc_insertion_point(one_of_clear_start:Schola.State)
  switch (optional_initial_state_case()) {
    case kInitialState: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.optional_initial_state_.initial_state_;
      }
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[1] = OPTIONAL_INITIAL_STATE_NOT_SET;
}


void State::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.State)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_optional_training_state();
  clear_optional_initial_state();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* State::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Schola.TrainingState training_state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_training_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.InitialState initial_state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_initial_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* State::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.State)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Schola.TrainingState training_state = 1;
  if (_internal_has_training_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::training_state(this),
        _Internal::training_state(this).GetCachedSize(), target, stream);
  }

  // .Schola.InitialState initial_state = 2;
  if (_internal_has_initial_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::initial_state(this),
        _Internal::initial_state(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.State)
  return target;
}

size_t State::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.State)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (optional_training_state_case()) {
    // .Schola.TrainingState training_state = 1;
    case kTrainingState: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.optional_training_state_.training_state_);
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  switch (optional_initial_state_case()) {
    // .Schola.InitialState initial_state = 2;
    case kInitialState: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.optional_initial_state_.initial_state_);
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData State::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    State::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*State::GetClassData() const { return &_class_data_; }


void State::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<State*>(&to_msg);
  auto& from = static_cast<const State&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.State)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.optional_training_state_case()) {
    case kTrainingState: {
      _this->_internal_mutable_training_state()->::Schola::TrainingState::MergeFrom(
          from._internal_training_state());
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  switch (from.optional_initial_state_case()) {
    case kInitialState: {
      _this->_internal_mutable_initial_state()->::Schola::InitialState::MergeFrom(
          from._internal_initial_state());
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void State::CopyFrom(const State& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.State)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool State::IsInitialized() const {
  return true;
}

void State::InternalSwap(State* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.optional_training_state_, other->_impl_.optional_training_state_);
  swap(_impl_.optional_initial_state_, other->_impl_.optional_initial_state_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
  swap(_impl_._oneof_case_[1], other->_impl_._oneof_case_[1]);
}

::PROTOBUF_NAMESPACE_ID::Metadata State::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_State_2eproto_getter, &descriptor_table_State_2eproto_once,
      file_level_metadata_State_2eproto[11]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Schola::AgentState_InfoEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::AgentState_InfoEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::AgentState_InfoEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::AgentState*
Arena::CreateMaybeMessage< ::Schola::AgentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::AgentState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::EnvironmentState_AgentStatesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::EnvironmentState_AgentStatesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::EnvironmentState_AgentStatesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::EnvironmentState*
Arena::CreateMaybeMessage< ::Schola::EnvironmentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::EnvironmentState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::TrainingState*
Arena::CreateMaybeMessage< ::Schola::TrainingState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::TrainingState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::InitialAgentState_InfoEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::InitialAgentState_InfoEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::InitialAgentState_InfoEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::InitialAgentState*
Arena::CreateMaybeMessage< ::Schola::InitialAgentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::InitialAgentState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::InitialEnvironmentState*
Arena::CreateMaybeMessage< ::Schola::InitialEnvironmentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::InitialEnvironmentState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::InitialState_EnvironmentStatesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::InitialState_EnvironmentStatesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::InitialState_EnvironmentStatesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::InitialState*
Arena::CreateMaybeMessage< ::Schola::InitialState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::InitialState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::State*
Arena::CreateMaybeMessage< ::Schola::State >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::State >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
