// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: State.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_State_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_State_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "Points.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_State_2eproto SCHOLAPROTOBUF_API
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct SCHOLAPROTOBUF_API TableStruct_State_2eproto {
  static const uint32_t offsets[];
};
SCHOLAPROTOBUF_API extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_State_2eproto;
namespace Schola {
class AgentState;
struct AgentStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern AgentStateDefaultTypeInternal _AgentState_default_instance_;
class AgentState_InfoEntry_DoNotUse;
struct AgentState_InfoEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern AgentState_InfoEntry_DoNotUseDefaultTypeInternal _AgentState_InfoEntry_DoNotUse_default_instance_;
class EnvironmentState;
struct EnvironmentStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern EnvironmentStateDefaultTypeInternal _EnvironmentState_default_instance_;
class EnvironmentState_AgentStatesEntry_DoNotUse;
struct EnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern EnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal _EnvironmentState_AgentStatesEntry_DoNotUse_default_instance_;
class InitialAgentState;
struct InitialAgentStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern InitialAgentStateDefaultTypeInternal _InitialAgentState_default_instance_;
class InitialAgentState_InfoEntry_DoNotUse;
struct InitialAgentState_InfoEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern InitialAgentState_InfoEntry_DoNotUseDefaultTypeInternal _InitialAgentState_InfoEntry_DoNotUse_default_instance_;
class InitialEnvironmentState;
struct InitialEnvironmentStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern InitialEnvironmentStateDefaultTypeInternal _InitialEnvironmentState_default_instance_;
class InitialEnvironmentState_AgentStatesEntry_DoNotUse;
struct InitialEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern InitialEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal _InitialEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_;
class InitialState;
struct InitialStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern InitialStateDefaultTypeInternal _InitialState_default_instance_;
class InitialState_EnvironmentStatesEntry_DoNotUse;
struct InitialState_EnvironmentStatesEntry_DoNotUseDefaultTypeInternal;
SCHOLAPROTOBUF_API extern InitialState_EnvironmentStatesEntry_DoNotUseDefaultTypeInternal _InitialState_EnvironmentStatesEntry_DoNotUse_default_instance_;
class State;
struct StateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern StateDefaultTypeInternal _State_default_instance_;
class TrainingState;
struct TrainingStateDefaultTypeInternal;
SCHOLAPROTOBUF_API extern TrainingStateDefaultTypeInternal _TrainingState_default_instance_;
}  // namespace Schola
PROTOBUF_NAMESPACE_OPEN
template<> SCHOLAPROTOBUF_API ::Schola::AgentState* Arena::CreateMaybeMessage<::Schola::AgentState>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::AgentState_InfoEntry_DoNotUse* Arena::CreateMaybeMessage<::Schola::AgentState_InfoEntry_DoNotUse>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::EnvironmentState* Arena::CreateMaybeMessage<::Schola::EnvironmentState>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::EnvironmentState_AgentStatesEntry_DoNotUse* Arena::CreateMaybeMessage<::Schola::EnvironmentState_AgentStatesEntry_DoNotUse>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::InitialAgentState* Arena::CreateMaybeMessage<::Schola::InitialAgentState>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::InitialAgentState_InfoEntry_DoNotUse* Arena::CreateMaybeMessage<::Schola::InitialAgentState_InfoEntry_DoNotUse>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::InitialEnvironmentState* Arena::CreateMaybeMessage<::Schola::InitialEnvironmentState>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse* Arena::CreateMaybeMessage<::Schola::InitialEnvironmentState_AgentStatesEntry_DoNotUse>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::InitialState* Arena::CreateMaybeMessage<::Schola::InitialState>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::InitialState_EnvironmentStatesEntry_DoNotUse* Arena::CreateMaybeMessage<::Schola::InitialState_EnvironmentStatesEntry_DoNotUse>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::State* Arena::CreateMaybeMessage<::Schola::State>(Arena*);
template<> SCHOLAPROTOBUF_API ::Schola::TrainingState* Arena::CreateMaybeMessage<::Schola::TrainingState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Schola {

// ===================================================================

class AgentState_InfoEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<AgentState_InfoEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<AgentState_InfoEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  AgentState_InfoEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR AgentState_InfoEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit AgentState_InfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const AgentState_InfoEntry_DoNotUse& other);
  static const AgentState_InfoEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const AgentState_InfoEntry_DoNotUse*>(&_AgentState_InfoEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "Schola.AgentState.InfoEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "Schola.AgentState.InfoEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_State_2eproto;
};

// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API AgentState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Schola.AgentState) */ {
 public:
  inline AgentState() : AgentState(nullptr) {}
  ~AgentState() override;
  explicit PROTOBUF_CONSTEXPR AgentState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgentState(const AgentState& from);
  AgentState(AgentState&& from) noexcept
    : AgentState() {
    *this = ::std::move(from);
  }

  inline AgentState& operator=(const AgentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgentState& operator=(AgentState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgentState& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgentState* internal_default_instance() {
    return reinterpret_cast<const AgentState*>(
               &_AgentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AgentState& a, AgentState& b) {
    a.Swap(&b);
  }
  inline void Swap(AgentState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgentState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgentState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgentState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgentState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AgentState& from) {
    AgentState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgentState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Schola.AgentState";
  }
  protected:
  explicit AgentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kInfoFieldNumber = 5,
    kObservationsFieldNumber = 1,
    kRewardFieldNumber = 2,
    kTerminatedFieldNumber = 3,
    kTruncatedFieldNumber = 4,
  };
  // map<string, string> info = 5;
  int info_size() const;
  private:
  int _internal_info_size() const;
  public:
  void clear_info();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_info() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_info();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      info() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_info();

  // .Schola.Point observations = 1;
  bool has_observations() const;
  private:
  bool _internal_has_observations() const;
  public:
  void clear_observations();
  const ::Schola::Point& observations() const;
  PROTOBUF_NODISCARD ::Schola::Point* release_observations();
  ::Schola::Point* mutable_observations();
  void set_allocated_observations(::Schola::Point* observations);
  private:
  const ::Schola::Point& _internal_observations() const;
  ::Schola::Point* _internal_mutable_observations();
  public:
  void unsafe_arena_set_allocated_observations(
      ::Schola::Point* observations);
  ::Schola::Point* unsafe_arena_release_observations();

  // float reward = 2;
  void clear_reward();
  float reward() const;
  void set_reward(float value);
  private:
  float _internal_reward() const;
  void _internal_set_reward(float value);
  public:

  // bool terminated = 3;
  void clear_terminated();
  bool terminated() const;
  void set_terminated(bool value);
  private:
  bool _internal_terminated() const;
  void _internal_set_terminated(bool value);
  public:

  // bool truncated = 4;
  void clear_truncated();
  bool truncated() const;
  void set_truncated(bool value);
  private:
  bool _internal_truncated() const;
  void _internal_set_truncated(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Schola.AgentState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        AgentState_InfoEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> info_;
    ::Schola::Point* observations_;
    float reward_;
    bool terminated_;
    bool truncated_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_State_2eproto;
};
// -------------------------------------------------------------------

class EnvironmentState_AgentStatesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<EnvironmentState_AgentStatesEntry_DoNotUse, 
    std::string, ::Schola::AgentState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<EnvironmentState_AgentStatesEntry_DoNotUse, 
    std::string, ::Schola::AgentState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  EnvironmentState_AgentStatesEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR EnvironmentState_AgentStatesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit EnvironmentState_AgentStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const EnvironmentState_AgentStatesEntry_DoNotUse& other);
  static const EnvironmentState_AgentStatesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const EnvironmentState_AgentStatesEntry_DoNotUse*>(&_EnvironmentState_AgentStatesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "Schola.EnvironmentState.AgentStatesEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_State_2eproto;
};

// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API EnvironmentState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Schola.EnvironmentState) */ {
 public:
  inline EnvironmentState() : EnvironmentState(nullptr) {}
  ~EnvironmentState() override;
  explicit PROTOBUF_CONSTEXPR EnvironmentState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EnvironmentState(const EnvironmentState& from);
  EnvironmentState(EnvironmentState&& from) noexcept
    : EnvironmentState() {
    *this = ::std::move(from);
  }

  inline EnvironmentState& operator=(const EnvironmentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnvironmentState& operator=(EnvironmentState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnvironmentState& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnvironmentState* internal_default_instance() {
    return reinterpret_cast<const EnvironmentState*>(
               &_EnvironmentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(EnvironmentState& a, EnvironmentState& b) {
    a.Swap(&b);
  }
  inline void Swap(EnvironmentState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnvironmentState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnvironmentState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EnvironmentState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EnvironmentState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EnvironmentState& from) {
    EnvironmentState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnvironmentState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Schola.EnvironmentState";
  }
  protected:
  explicit EnvironmentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kAgentStatesFieldNumber = 1,
  };
  // map<string, .Schola.AgentState> agent_states = 1;
  int agent_states_size() const;
  private:
  int _internal_agent_states_size() const;
  public:
  void clear_agent_states();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >&
      _internal_agent_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >*
      _internal_mutable_agent_states();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >&
      agent_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >*
      mutable_agent_states();

  // @@protoc_insertion_point(class_scope:Schola.EnvironmentState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        EnvironmentState_AgentStatesEntry_DoNotUse,
        std::string, ::Schola::AgentState,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> agent_states_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_State_2eproto;
};
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API TrainingState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Schola.TrainingState) */ {
 public:
  inline TrainingState() : TrainingState(nullptr) {}
  ~TrainingState() override;
  explicit PROTOBUF_CONSTEXPR TrainingState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrainingState(const TrainingState& from);
  TrainingState(TrainingState&& from) noexcept
    : TrainingState() {
    *this = ::std::move(from);
  }

  inline TrainingState& operator=(const TrainingState& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainingState& operator=(TrainingState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrainingState& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrainingState* internal_default_instance() {
    return reinterpret_cast<const TrainingState*>(
               &_TrainingState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TrainingState& a, TrainingState& b) {
    a.Swap(&b);
  }
  inline void Swap(TrainingState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainingState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrainingState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrainingState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrainingState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrainingState& from) {
    TrainingState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrainingState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Schola.TrainingState";
  }
  protected:
  explicit TrainingState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEnvironmentStatesFieldNumber = 1,
  };
  // repeated .Schola.EnvironmentState environment_states = 1;
  int environment_states_size() const;
  private:
  int _internal_environment_states_size() const;
  public:
  void clear_environment_states();
  ::Schola::EnvironmentState* mutable_environment_states(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Schola::EnvironmentState >*
      mutable_environment_states();
  private:
  const ::Schola::EnvironmentState& _internal_environment_states(int index) const;
  ::Schola::EnvironmentState* _internal_add_environment_states();
  public:
  const ::Schola::EnvironmentState& environment_states(int index) const;
  ::Schola::EnvironmentState* add_environment_states();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Schola::EnvironmentState >&
      environment_states() const;

  // @@protoc_insertion_point(class_scope:Schola.TrainingState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Schola::EnvironmentState > environment_states_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_State_2eproto;
};
// -------------------------------------------------------------------

class InitialAgentState_InfoEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InitialAgentState_InfoEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InitialAgentState_InfoEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  InitialAgentState_InfoEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR InitialAgentState_InfoEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit InitialAgentState_InfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const InitialAgentState_InfoEntry_DoNotUse& other);
  static const InitialAgentState_InfoEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InitialAgentState_InfoEntry_DoNotUse*>(&_InitialAgentState_InfoEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "Schola.InitialAgentState.InfoEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "Schola.InitialAgentState.InfoEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_State_2eproto;
};

// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API InitialAgentState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Schola.InitialAgentState) */ {
 public:
  inline InitialAgentState() : InitialAgentState(nullptr) {}
  ~InitialAgentState() override;
  explicit PROTOBUF_CONSTEXPR InitialAgentState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InitialAgentState(const InitialAgentState& from);
  InitialAgentState(InitialAgentState&& from) noexcept
    : InitialAgentState() {
    *this = ::std::move(from);
  }

  inline InitialAgentState& operator=(const InitialAgentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline InitialAgentState& operator=(InitialAgentState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InitialAgentState& default_instance() {
    return *internal_default_instance();
  }
  static inline const InitialAgentState* internal_default_instance() {
    return reinterpret_cast<const InitialAgentState*>(
               &_InitialAgentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(InitialAgentState& a, InitialAgentState& b) {
    a.Swap(&b);
  }
  inline void Swap(InitialAgentState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InitialAgentState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InitialAgentState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InitialAgentState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InitialAgentState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InitialAgentState& from) {
    InitialAgentState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InitialAgentState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Schola.InitialAgentState";
  }
  protected:
  explicit InitialAgentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kInfoFieldNumber = 4,
    kObservationsFieldNumber = 1,
  };
  // map<string, string> info = 4;
  int info_size() const;
  private:
  int _internal_info_size() const;
  public:
  void clear_info();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_info() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_info();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      info() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_info();

  // .Schola.Point observations = 1;
  bool has_observations() const;
  private:
  bool _internal_has_observations() const;
  public:
  void clear_observations();
  const ::Schola::Point& observations() const;
  PROTOBUF_NODISCARD ::Schola::Point* release_observations();
  ::Schola::Point* mutable_observations();
  void set_allocated_observations(::Schola::Point* observations);
  private:
  const ::Schola::Point& _internal_observations() const;
  ::Schola::Point* _internal_mutable_observations();
  public:
  void unsafe_arena_set_allocated_observations(
      ::Schola::Point* observations);
  ::Schola::Point* unsafe_arena_release_observations();

  // @@protoc_insertion_point(class_scope:Schola.InitialAgentState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        InitialAgentState_InfoEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> info_;
    ::Schola::Point* observations_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_State_2eproto;
};
// -------------------------------------------------------------------

class InitialEnvironmentState_AgentStatesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InitialEnvironmentState_AgentStatesEntry_DoNotUse, 
    std::string, ::Schola::InitialAgentState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InitialEnvironmentState_AgentStatesEntry_DoNotUse, 
    std::string, ::Schola::InitialAgentState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  InitialEnvironmentState_AgentStatesEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR InitialEnvironmentState_AgentStatesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit InitialEnvironmentState_AgentStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const InitialEnvironmentState_AgentStatesEntry_DoNotUse& other);
  static const InitialEnvironmentState_AgentStatesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InitialEnvironmentState_AgentStatesEntry_DoNotUse*>(&_InitialEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "Schola.InitialEnvironmentState.AgentStatesEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_State_2eproto;
};

// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API InitialEnvironmentState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Schola.InitialEnvironmentState) */ {
 public:
  inline InitialEnvironmentState() : InitialEnvironmentState(nullptr) {}
  ~InitialEnvironmentState() override;
  explicit PROTOBUF_CONSTEXPR InitialEnvironmentState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InitialEnvironmentState(const InitialEnvironmentState& from);
  InitialEnvironmentState(InitialEnvironmentState&& from) noexcept
    : InitialEnvironmentState() {
    *this = ::std::move(from);
  }

  inline InitialEnvironmentState& operator=(const InitialEnvironmentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline InitialEnvironmentState& operator=(InitialEnvironmentState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InitialEnvironmentState& default_instance() {
    return *internal_default_instance();
  }
  static inline const InitialEnvironmentState* internal_default_instance() {
    return reinterpret_cast<const InitialEnvironmentState*>(
               &_InitialEnvironmentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(InitialEnvironmentState& a, InitialEnvironmentState& b) {
    a.Swap(&b);
  }
  inline void Swap(InitialEnvironmentState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InitialEnvironmentState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InitialEnvironmentState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InitialEnvironmentState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InitialEnvironmentState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InitialEnvironmentState& from) {
    InitialEnvironmentState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InitialEnvironmentState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Schola.InitialEnvironmentState";
  }
  protected:
  explicit InitialEnvironmentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kAgentStatesFieldNumber = 1,
  };
  // map<string, .Schola.InitialAgentState> agent_states = 1;
  int agent_states_size() const;
  private:
  int _internal_agent_states_size() const;
  public:
  void clear_agent_states();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >&
      _internal_agent_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >*
      _internal_mutable_agent_states();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >&
      agent_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >*
      mutable_agent_states();

  // @@protoc_insertion_point(class_scope:Schola.InitialEnvironmentState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        InitialEnvironmentState_AgentStatesEntry_DoNotUse,
        std::string, ::Schola::InitialAgentState,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> agent_states_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_State_2eproto;
};
// -------------------------------------------------------------------

class InitialState_EnvironmentStatesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InitialState_EnvironmentStatesEntry_DoNotUse, 
    int32_t, ::Schola::InitialEnvironmentState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InitialState_EnvironmentStatesEntry_DoNotUse, 
    int32_t, ::Schola::InitialEnvironmentState,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  InitialState_EnvironmentStatesEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR InitialState_EnvironmentStatesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit InitialState_EnvironmentStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const InitialState_EnvironmentStatesEntry_DoNotUse& other);
  static const InitialState_EnvironmentStatesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InitialState_EnvironmentStatesEntry_DoNotUse*>(&_InitialState_EnvironmentStatesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_State_2eproto;
};

// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API InitialState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Schola.InitialState) */ {
 public:
  inline InitialState() : InitialState(nullptr) {}
  ~InitialState() override;
  explicit PROTOBUF_CONSTEXPR InitialState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InitialState(const InitialState& from);
  InitialState(InitialState&& from) noexcept
    : InitialState() {
    *this = ::std::move(from);
  }

  inline InitialState& operator=(const InitialState& from) {
    CopyFrom(from);
    return *this;
  }
  inline InitialState& operator=(InitialState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InitialState& default_instance() {
    return *internal_default_instance();
  }
  static inline const InitialState* internal_default_instance() {
    return reinterpret_cast<const InitialState*>(
               &_InitialState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(InitialState& a, InitialState& b) {
    a.Swap(&b);
  }
  inline void Swap(InitialState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InitialState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InitialState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InitialState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InitialState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InitialState& from) {
    InitialState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InitialState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Schola.InitialState";
  }
  protected:
  explicit InitialState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kEnvironmentStatesFieldNumber = 1,
  };
  // map<int32, .Schola.InitialEnvironmentState> environment_states = 1;
  int environment_states_size() const;
  private:
  int _internal_environment_states_size() const;
  public:
  void clear_environment_states();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >&
      _internal_environment_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >*
      _internal_mutable_environment_states();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >&
      environment_states() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >*
      mutable_environment_states();

  // @@protoc_insertion_point(class_scope:Schola.InitialState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        InitialState_EnvironmentStatesEntry_DoNotUse,
        int32_t, ::Schola::InitialEnvironmentState,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> environment_states_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_State_2eproto;
};
// -------------------------------------------------------------------

class SCHOLAPROTOBUF_API State final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Schola.State) */ {
 public:
  inline State() : State(nullptr) {}
  ~State() override;
  explicit PROTOBUF_CONSTEXPR State(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  State(const State& from);
  State(State&& from) noexcept
    : State() {
    *this = ::std::move(from);
  }

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }
  inline State& operator=(State&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const State& default_instance() {
    return *internal_default_instance();
  }
  enum OptionalTrainingStateCase {
    kTrainingState = 1,
    OPTIONAL_TRAINING_STATE_NOT_SET = 0,
  };

  enum OptionalInitialStateCase {
    kInitialState = 2,
    OPTIONAL_INITIAL_STATE_NOT_SET = 0,
  };

  static inline const State* internal_default_instance() {
    return reinterpret_cast<const State*>(
               &_State_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  friend void swap(State& a, State& b) {
    a.Swap(&b);
  }
  inline void Swap(State* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(State* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  State* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<State>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const State& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const State& from) {
    State::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(State* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Schola.State";
  }
  protected:
  explicit State(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTrainingStateFieldNumber = 1,
    kInitialStateFieldNumber = 2,
  };
  // .Schola.TrainingState training_state = 1;
  bool has_training_state() const;
  private:
  bool _internal_has_training_state() const;
  public:
  void clear_training_state();
  const ::Schola::TrainingState& training_state() const;
  PROTOBUF_NODISCARD ::Schola::TrainingState* release_training_state();
  ::Schola::TrainingState* mutable_training_state();
  void set_allocated_training_state(::Schola::TrainingState* training_state);
  private:
  const ::Schola::TrainingState& _internal_training_state() const;
  ::Schola::TrainingState* _internal_mutable_training_state();
  public:
  void unsafe_arena_set_allocated_training_state(
      ::Schola::TrainingState* training_state);
  ::Schola::TrainingState* unsafe_arena_release_training_state();

  // .Schola.InitialState initial_state = 2;
  bool has_initial_state() const;
  private:
  bool _internal_has_initial_state() const;
  public:
  void clear_initial_state();
  const ::Schola::InitialState& initial_state() const;
  PROTOBUF_NODISCARD ::Schola::InitialState* release_initial_state();
  ::Schola::InitialState* mutable_initial_state();
  void set_allocated_initial_state(::Schola::InitialState* initial_state);
  private:
  const ::Schola::InitialState& _internal_initial_state() const;
  ::Schola::InitialState* _internal_mutable_initial_state();
  public:
  void unsafe_arena_set_allocated_initial_state(
      ::Schola::InitialState* initial_state);
  ::Schola::InitialState* unsafe_arena_release_initial_state();

  void clear_optional_training_state();
  OptionalTrainingStateCase optional_training_state_case() const;
  void clear_optional_initial_state();
  OptionalInitialStateCase optional_initial_state_case() const;
  // @@protoc_insertion_point(class_scope:Schola.State)
 private:
  class _Internal;
  void set_has_training_state();
  void set_has_initial_state();

  inline bool has_optional_training_state() const;
  inline void clear_has_optional_training_state();

  inline bool has_optional_initial_state() const;
  inline void clear_has_optional_initial_state();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union OptionalTrainingStateUnion {
      constexpr OptionalTrainingStateUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::Schola::TrainingState* training_state_;
    } optional_training_state_;
    union OptionalInitialStateUnion {
      constexpr OptionalInitialStateUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::Schola::InitialState* initial_state_;
    } optional_initial_state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[2];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_State_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AgentState

// .Schola.Point observations = 1;
inline bool AgentState::_internal_has_observations() const {
  return this != internal_default_instance() && _impl_.observations_ != nullptr;
}
inline bool AgentState::has_observations() const {
  return _internal_has_observations();
}
inline const ::Schola::Point& AgentState::_internal_observations() const {
  const ::Schola::Point* p = _impl_.observations_;
  return p != nullptr ? *p : reinterpret_cast<const ::Schola::Point&>(
      ::Schola::_Point_default_instance_);
}
inline const ::Schola::Point& AgentState::observations() const {
  // @@protoc_insertion_point(field_get:Schola.AgentState.observations)
  return _internal_observations();
}
inline void AgentState::unsafe_arena_set_allocated_observations(
    ::Schola::Point* observations) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.observations_);
  }
  _impl_.observations_ = observations;
  if (observations) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.AgentState.observations)
}
inline ::Schola::Point* AgentState::release_observations() {
  
  ::Schola::Point* temp = _impl_.observations_;
  _impl_.observations_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Schola::Point* AgentState::unsafe_arena_release_observations() {
  // @@protoc_insertion_point(field_release:Schola.AgentState.observations)
  
  ::Schola::Point* temp = _impl_.observations_;
  _impl_.observations_ = nullptr;
  return temp;
}
inline ::Schola::Point* AgentState::_internal_mutable_observations() {
  
  if (_impl_.observations_ == nullptr) {
    auto* p = CreateMaybeMessage<::Schola::Point>(GetArenaForAllocation());
    _impl_.observations_ = p;
  }
  return _impl_.observations_;
}
inline ::Schola::Point* AgentState::mutable_observations() {
  ::Schola::Point* _msg = _internal_mutable_observations();
  // @@protoc_insertion_point(field_mutable:Schola.AgentState.observations)
  return _msg;
}
inline void AgentState::set_allocated_observations(::Schola::Point* observations) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.observations_);
  }
  if (observations) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(observations));
    if (message_arena != submessage_arena) {
      observations = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, observations, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.observations_ = observations;
  // @@protoc_insertion_point(field_set_allocated:Schola.AgentState.observations)
}

// float reward = 2;
inline void AgentState::clear_reward() {
  _impl_.reward_ = 0;
}
inline float AgentState::_internal_reward() const {
  return _impl_.reward_;
}
inline float AgentState::reward() const {
  // @@protoc_insertion_point(field_get:Schola.AgentState.reward)
  return _internal_reward();
}
inline void AgentState::_internal_set_reward(float value) {
  
  _impl_.reward_ = value;
}
inline void AgentState::set_reward(float value) {
  _internal_set_reward(value);
  // @@protoc_insertion_point(field_set:Schola.AgentState.reward)
}

// bool terminated = 3;
inline void AgentState::clear_terminated() {
  _impl_.terminated_ = false;
}
inline bool AgentState::_internal_terminated() const {
  return _impl_.terminated_;
}
inline bool AgentState::terminated() const {
  // @@protoc_insertion_point(field_get:Schola.AgentState.terminated)
  return _internal_terminated();
}
inline void AgentState::_internal_set_terminated(bool value) {
  
  _impl_.terminated_ = value;
}
inline void AgentState::set_terminated(bool value) {
  _internal_set_terminated(value);
  // @@protoc_insertion_point(field_set:Schola.AgentState.terminated)
}

// bool truncated = 4;
inline void AgentState::clear_truncated() {
  _impl_.truncated_ = false;
}
inline bool AgentState::_internal_truncated() const {
  return _impl_.truncated_;
}
inline bool AgentState::truncated() const {
  // @@protoc_insertion_point(field_get:Schola.AgentState.truncated)
  return _internal_truncated();
}
inline void AgentState::_internal_set_truncated(bool value) {
  
  _impl_.truncated_ = value;
}
inline void AgentState::set_truncated(bool value) {
  _internal_set_truncated(value);
  // @@protoc_insertion_point(field_set:Schola.AgentState.truncated)
}

// map<string, string> info = 5;
inline int AgentState::_internal_info_size() const {
  return _impl_.info_.size();
}
inline int AgentState::info_size() const {
  return _internal_info_size();
}
inline void AgentState::clear_info() {
  _impl_.info_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
AgentState::_internal_info() const {
  return _impl_.info_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
AgentState::info() const {
  // @@protoc_insertion_point(field_map:Schola.AgentState.info)
  return _internal_info();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
AgentState::_internal_mutable_info() {
  return _impl_.info_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
AgentState::mutable_info() {
  // @@protoc_insertion_point(field_mutable_map:Schola.AgentState.info)
  return _internal_mutable_info();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// EnvironmentState

// map<string, .Schola.AgentState> agent_states = 1;
inline int EnvironmentState::_internal_agent_states_size() const {
  return _impl_.agent_states_.size();
}
inline int EnvironmentState::agent_states_size() const {
  return _internal_agent_states_size();
}
inline void EnvironmentState::clear_agent_states() {
  _impl_.agent_states_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >&
EnvironmentState::_internal_agent_states() const {
  return _impl_.agent_states_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >&
EnvironmentState::agent_states() const {
  // @@protoc_insertion_point(field_map:Schola.EnvironmentState.agent_states)
  return _internal_agent_states();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >*
EnvironmentState::_internal_mutable_agent_states() {
  return _impl_.agent_states_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::AgentState >*
EnvironmentState::mutable_agent_states() {
  // @@protoc_insertion_point(field_mutable_map:Schola.EnvironmentState.agent_states)
  return _internal_mutable_agent_states();
}

// -------------------------------------------------------------------

// TrainingState

// repeated .Schola.EnvironmentState environment_states = 1;
inline int TrainingState::_internal_environment_states_size() const {
  return _impl_.environment_states_.size();
}
inline int TrainingState::environment_states_size() const {
  return _internal_environment_states_size();
}
inline void TrainingState::clear_environment_states() {
  _impl_.environment_states_.Clear();
}
inline ::Schola::EnvironmentState* TrainingState::mutable_environment_states(int index) {
  // @@protoc_insertion_point(field_mutable:Schola.TrainingState.environment_states)
  return _impl_.environment_states_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Schola::EnvironmentState >*
TrainingState::mutable_environment_states() {
  // @@protoc_insertion_point(field_mutable_list:Schola.TrainingState.environment_states)
  return &_impl_.environment_states_;
}
inline const ::Schola::EnvironmentState& TrainingState::_internal_environment_states(int index) const {
  return _impl_.environment_states_.Get(index);
}
inline const ::Schola::EnvironmentState& TrainingState::environment_states(int index) const {
  // @@protoc_insertion_point(field_get:Schola.TrainingState.environment_states)
  return _internal_environment_states(index);
}
inline ::Schola::EnvironmentState* TrainingState::_internal_add_environment_states() {
  return _impl_.environment_states_.Add();
}
inline ::Schola::EnvironmentState* TrainingState::add_environment_states() {
  ::Schola::EnvironmentState* _add = _internal_add_environment_states();
  // @@protoc_insertion_point(field_add:Schola.TrainingState.environment_states)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Schola::EnvironmentState >&
TrainingState::environment_states() const {
  // @@protoc_insertion_point(field_list:Schola.TrainingState.environment_states)
  return _impl_.environment_states_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// InitialAgentState

// .Schola.Point observations = 1;
inline bool InitialAgentState::_internal_has_observations() const {
  return this != internal_default_instance() && _impl_.observations_ != nullptr;
}
inline bool InitialAgentState::has_observations() const {
  return _internal_has_observations();
}
inline const ::Schola::Point& InitialAgentState::_internal_observations() const {
  const ::Schola::Point* p = _impl_.observations_;
  return p != nullptr ? *p : reinterpret_cast<const ::Schola::Point&>(
      ::Schola::_Point_default_instance_);
}
inline const ::Schola::Point& InitialAgentState::observations() const {
  // @@protoc_insertion_point(field_get:Schola.InitialAgentState.observations)
  return _internal_observations();
}
inline void InitialAgentState::unsafe_arena_set_allocated_observations(
    ::Schola::Point* observations) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.observations_);
  }
  _impl_.observations_ = observations;
  if (observations) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.InitialAgentState.observations)
}
inline ::Schola::Point* InitialAgentState::release_observations() {
  
  ::Schola::Point* temp = _impl_.observations_;
  _impl_.observations_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Schola::Point* InitialAgentState::unsafe_arena_release_observations() {
  // @@protoc_insertion_point(field_release:Schola.InitialAgentState.observations)
  
  ::Schola::Point* temp = _impl_.observations_;
  _impl_.observations_ = nullptr;
  return temp;
}
inline ::Schola::Point* InitialAgentState::_internal_mutable_observations() {
  
  if (_impl_.observations_ == nullptr) {
    auto* p = CreateMaybeMessage<::Schola::Point>(GetArenaForAllocation());
    _impl_.observations_ = p;
  }
  return _impl_.observations_;
}
inline ::Schola::Point* InitialAgentState::mutable_observations() {
  ::Schola::Point* _msg = _internal_mutable_observations();
  // @@protoc_insertion_point(field_mutable:Schola.InitialAgentState.observations)
  return _msg;
}
inline void InitialAgentState::set_allocated_observations(::Schola::Point* observations) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.observations_);
  }
  if (observations) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(observations));
    if (message_arena != submessage_arena) {
      observations = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, observations, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.observations_ = observations;
  // @@protoc_insertion_point(field_set_allocated:Schola.InitialAgentState.observations)
}

// map<string, string> info = 4;
inline int InitialAgentState::_internal_info_size() const {
  return _impl_.info_.size();
}
inline int InitialAgentState::info_size() const {
  return _internal_info_size();
}
inline void InitialAgentState::clear_info() {
  _impl_.info_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
InitialAgentState::_internal_info() const {
  return _impl_.info_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
InitialAgentState::info() const {
  // @@protoc_insertion_point(field_map:Schola.InitialAgentState.info)
  return _internal_info();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
InitialAgentState::_internal_mutable_info() {
  return _impl_.info_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
InitialAgentState::mutable_info() {
  // @@protoc_insertion_point(field_mutable_map:Schola.InitialAgentState.info)
  return _internal_mutable_info();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// InitialEnvironmentState

// map<string, .Schola.InitialAgentState> agent_states = 1;
inline int InitialEnvironmentState::_internal_agent_states_size() const {
  return _impl_.agent_states_.size();
}
inline int InitialEnvironmentState::agent_states_size() const {
  return _internal_agent_states_size();
}
inline void InitialEnvironmentState::clear_agent_states() {
  _impl_.agent_states_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >&
InitialEnvironmentState::_internal_agent_states() const {
  return _impl_.agent_states_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >&
InitialEnvironmentState::agent_states() const {
  // @@protoc_insertion_point(field_map:Schola.InitialEnvironmentState.agent_states)
  return _internal_agent_states();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >*
InitialEnvironmentState::_internal_mutable_agent_states() {
  return _impl_.agent_states_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::InitialAgentState >*
InitialEnvironmentState::mutable_agent_states() {
  // @@protoc_insertion_point(field_mutable_map:Schola.InitialEnvironmentState.agent_states)
  return _internal_mutable_agent_states();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// InitialState

// map<int32, .Schola.InitialEnvironmentState> environment_states = 1;
inline int InitialState::_internal_environment_states_size() const {
  return _impl_.environment_states_.size();
}
inline int InitialState::environment_states_size() const {
  return _internal_environment_states_size();
}
inline void InitialState::clear_environment_states() {
  _impl_.environment_states_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >&
InitialState::_internal_environment_states() const {
  return _impl_.environment_states_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >&
InitialState::environment_states() const {
  // @@protoc_insertion_point(field_map:Schola.InitialState.environment_states)
  return _internal_environment_states();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >*
InitialState::_internal_mutable_environment_states() {
  return _impl_.environment_states_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::Schola::InitialEnvironmentState >*
InitialState::mutable_environment_states() {
  // @@protoc_insertion_point(field_mutable_map:Schola.InitialState.environment_states)
  return _internal_mutable_environment_states();
}

// -------------------------------------------------------------------

// State

// .Schola.TrainingState training_state = 1;
inline bool State::_internal_has_training_state() const {
  return optional_training_state_case() == kTrainingState;
}
inline bool State::has_training_state() const {
  return _internal_has_training_state();
}
inline void State::set_has_training_state() {
  _impl_._oneof_case_[0] = kTrainingState;
}
inline void State::clear_training_state() {
  if (_internal_has_training_state()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.optional_training_state_.training_state_;
    }
    clear_has_optional_training_state();
  }
}
inline ::Schola::TrainingState* State::release_training_state() {
  // @@protoc_insertion_point(field_release:Schola.State.training_state)
  if (_internal_has_training_state()) {
    clear_has_optional_training_state();
    ::Schola::TrainingState* temp = _impl_.optional_training_state_.training_state_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.optional_training_state_.training_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::TrainingState& State::_internal_training_state() const {
  return _internal_has_training_state()
      ? *_impl_.optional_training_state_.training_state_
      : reinterpret_cast< ::Schola::TrainingState&>(::Schola::_TrainingState_default_instance_);
}
inline const ::Schola::TrainingState& State::training_state() const {
  // @@protoc_insertion_point(field_get:Schola.State.training_state)
  return _internal_training_state();
}
inline ::Schola::TrainingState* State::unsafe_arena_release_training_state() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.State.training_state)
  if (_internal_has_training_state()) {
    clear_has_optional_training_state();
    ::Schola::TrainingState* temp = _impl_.optional_training_state_.training_state_;
    _impl_.optional_training_state_.training_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void State::unsafe_arena_set_allocated_training_state(::Schola::TrainingState* training_state) {
  clear_optional_training_state();
  if (training_state) {
    set_has_training_state();
    _impl_.optional_training_state_.training_state_ = training_state;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.State.training_state)
}
inline ::Schola::TrainingState* State::_internal_mutable_training_state() {
  if (!_internal_has_training_state()) {
    clear_optional_training_state();
    set_has_training_state();
    _impl_.optional_training_state_.training_state_ = CreateMaybeMessage< ::Schola::TrainingState >(GetArenaForAllocation());
  }
  return _impl_.optional_training_state_.training_state_;
}
inline ::Schola::TrainingState* State::mutable_training_state() {
  ::Schola::TrainingState* _msg = _internal_mutable_training_state();
  // @@protoc_insertion_point(field_mutable:Schola.State.training_state)
  return _msg;
}

// .Schola.InitialState initial_state = 2;
inline bool State::_internal_has_initial_state() const {
  return optional_initial_state_case() == kInitialState;
}
inline bool State::has_initial_state() const {
  return _internal_has_initial_state();
}
inline void State::set_has_initial_state() {
  _impl_._oneof_case_[1] = kInitialState;
}
inline void State::clear_initial_state() {
  if (_internal_has_initial_state()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.optional_initial_state_.initial_state_;
    }
    clear_has_optional_initial_state();
  }
}
inline ::Schola::InitialState* State::release_initial_state() {
  // @@protoc_insertion_point(field_release:Schola.State.initial_state)
  if (_internal_has_initial_state()) {
    clear_has_optional_initial_state();
    ::Schola::InitialState* temp = _impl_.optional_initial_state_.initial_state_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.optional_initial_state_.initial_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Schola::InitialState& State::_internal_initial_state() const {
  return _internal_has_initial_state()
      ? *_impl_.optional_initial_state_.initial_state_
      : reinterpret_cast< ::Schola::InitialState&>(::Schola::_InitialState_default_instance_);
}
inline const ::Schola::InitialState& State::initial_state() const {
  // @@protoc_insertion_point(field_get:Schola.State.initial_state)
  return _internal_initial_state();
}
inline ::Schola::InitialState* State::unsafe_arena_release_initial_state() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Schola.State.initial_state)
  if (_internal_has_initial_state()) {
    clear_has_optional_initial_state();
    ::Schola::InitialState* temp = _impl_.optional_initial_state_.initial_state_;
    _impl_.optional_initial_state_.initial_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void State::unsafe_arena_set_allocated_initial_state(::Schola::InitialState* initial_state) {
  clear_optional_initial_state();
  if (initial_state) {
    set_has_initial_state();
    _impl_.optional_initial_state_.initial_state_ = initial_state;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Schola.State.initial_state)
}
inline ::Schola::InitialState* State::_internal_mutable_initial_state() {
  if (!_internal_has_initial_state()) {
    clear_optional_initial_state();
    set_has_initial_state();
    _impl_.optional_initial_state_.initial_state_ = CreateMaybeMessage< ::Schola::InitialState >(GetArenaForAllocation());
  }
  return _impl_.optional_initial_state_.initial_state_;
}
inline ::Schola::InitialState* State::mutable_initial_state() {
  ::Schola::InitialState* _msg = _internal_mutable_initial_state();
  // @@protoc_insertion_point(field_mutable:Schola.State.initial_state)
  return _msg;
}

inline bool State::has_optional_training_state() const {
  return optional_training_state_case() != OPTIONAL_TRAINING_STATE_NOT_SET;
}
inline void State::clear_has_optional_training_state() {
  _impl_._oneof_case_[0] = OPTIONAL_TRAINING_STATE_NOT_SET;
}
inline bool State::has_optional_initial_state() const {
  return optional_initial_state_case() != OPTIONAL_INITIAL_STATE_NOT_SET;
}
inline void State::clear_has_optional_initial_state() {
  _impl_._oneof_case_[1] = OPTIONAL_INITIAL_STATE_NOT_SET;
}
inline State::OptionalTrainingStateCase State::optional_training_state_case() const {
  return State::OptionalTrainingStateCase(_impl_._oneof_case_[0]);
}
inline State::OptionalInitialStateCase State::optional_initial_state_case() const {
  return State::OptionalInitialStateCase(_impl_._oneof_case_[1]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Schola

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_State_2eproto
