// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImitationState.proto

#pragma warning (disable : 4800)
#pragma warning (disable : 4125)
#include "ImitationState.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Schola {
PROTOBUF_CONSTEXPR ImitationAgentState_InfoEntry_DoNotUse::ImitationAgentState_InfoEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct ImitationAgentState_InfoEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImitationAgentState_InfoEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImitationAgentState_InfoEntry_DoNotUseDefaultTypeInternal() {}
  union {
    ImitationAgentState_InfoEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImitationAgentState_InfoEntry_DoNotUseDefaultTypeInternal _ImitationAgentState_InfoEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR ImitationAgentState::ImitationAgentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.info_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.observations_)*/nullptr
  , /*decltype(_impl_.actions_)*/nullptr
  , /*decltype(_impl_.reward_)*/0
  , /*decltype(_impl_.terminated_)*/false
  , /*decltype(_impl_.truncated_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ImitationAgentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImitationAgentStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImitationAgentStateDefaultTypeInternal() {}
  union {
    ImitationAgentState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImitationAgentStateDefaultTypeInternal _ImitationAgentState_default_instance_;
PROTOBUF_CONSTEXPR ImitationEnvironmentState_AgentStatesEntry_DoNotUse::ImitationEnvironmentState_AgentStatesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct ImitationEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImitationEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImitationEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    ImitationEnvironmentState_AgentStatesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImitationEnvironmentState_AgentStatesEntry_DoNotUseDefaultTypeInternal _ImitationEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR ImitationEnvironmentState::ImitationEnvironmentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.agent_states_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ImitationEnvironmentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImitationEnvironmentStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImitationEnvironmentStateDefaultTypeInternal() {}
  union {
    ImitationEnvironmentState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImitationEnvironmentStateDefaultTypeInternal _ImitationEnvironmentState_default_instance_;
PROTOBUF_CONSTEXPR ImitationTrainingState::ImitationTrainingState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.environment_states_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ImitationTrainingStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImitationTrainingStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImitationTrainingStateDefaultTypeInternal() {}
  union {
    ImitationTrainingState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImitationTrainingStateDefaultTypeInternal _ImitationTrainingState_default_instance_;
PROTOBUF_CONSTEXPR ImitationState::ImitationState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.optional_training_state_)*/{}
  , /*decltype(_impl_.optional_initial_state_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct ImitationStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImitationStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImitationStateDefaultTypeInternal() {}
  union {
    ImitationState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImitationStateDefaultTypeInternal _ImitationState_default_instance_;
}  // namespace Schola
static ::_pb::Metadata file_level_metadata_ImitationState_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ImitationState_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ImitationState_2eproto = nullptr;

const uint32_t TableStruct_ImitationState_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState_InfoEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState_InfoEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState_InfoEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState_InfoEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState, _impl_.observations_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState, _impl_.reward_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState, _impl_.terminated_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState, _impl_.truncated_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState, _impl_.info_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationAgentState, _impl_.actions_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationEnvironmentState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationEnvironmentState, _impl_.agent_states_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationTrainingState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationTrainingState, _impl_.environment_states_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationState, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationState, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationState, _impl_.optional_training_state_),
  PROTOBUF_FIELD_OFFSET(::Schola::ImitationState, _impl_.optional_initial_state_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::Schola::ImitationAgentState_InfoEntry_DoNotUse)},
  { 10, -1, -1, sizeof(::Schola::ImitationAgentState)},
  { 22, 30, -1, sizeof(::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse)},
  { 32, -1, -1, sizeof(::Schola::ImitationEnvironmentState)},
  { 39, -1, -1, sizeof(::Schola::ImitationTrainingState)},
  { 46, -1, -1, sizeof(::Schola::ImitationState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Schola::_ImitationAgentState_InfoEntry_DoNotUse_default_instance_._instance,
  &::Schola::_ImitationAgentState_default_instance_._instance,
  &::Schola::_ImitationEnvironmentState_AgentStatesEntry_DoNotUse_default_instance_._instance,
  &::Schola::_ImitationEnvironmentState_default_instance_._instance,
  &::Schola::_ImitationTrainingState_default_instance_._instance,
  &::Schola::_ImitationState_default_instance_._instance,
};

const char descriptor_table_protodef_ImitationState_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024ImitationState.proto\022\006Schola\032\014Points.p"
  "roto\032\013State.proto\"\363\001\n\023ImitationAgentStat"
  "e\022#\n\014observations\030\001 \001(\0132\r.Schola.Point\022\016"
  "\n\006reward\030\002 \001(\002\022\022\n\nterminated\030\003 \001(\010\022\021\n\ttr"
  "uncated\030\004 \001(\010\0223\n\004info\030\005 \003(\0132%.Schola.Imi"
  "tationAgentState.InfoEntry\022\036\n\007actions\030\006 "
  "\001(\0132\r.Schola.Point\032+\n\tInfoEntry\022\013\n\003key\030\001"
  " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\266\001\n\031ImitationEnv"
  "ironmentState\022H\n\014agent_states\030\001 \003(\01322.Sc"
  "hola.ImitationEnvironmentState.AgentStat"
  "esEntry\032O\n\020AgentStatesEntry\022\013\n\003key\030\001 \001(\t"
  "\022*\n\005value\030\002 \001(\0132\033.Schola.ImitationAgentS"
  "tate:\0028\001\"W\n\026ImitationTrainingState\022=\n\022en"
  "vironment_states\030\001 \003(\0132!.Schola.Imitatio"
  "nEnvironmentState\"\256\001\n\016ImitationState\0228\n\016"
  "training_state\030\001 \001(\0132\036.Schola.ImitationT"
  "rainingStateH\000\022-\n\rinitial_state\030\002 \001(\0132\024."
  "Schola.InitialStateH\001B\031\n\027optional_traini"
  "ng_stateB\030\n\026optional_initial_stateb\006prot"
  "o3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_ImitationState_2eproto_deps[2] = {
  &::descriptor_table_Points_2eproto,
  &::descriptor_table_State_2eproto,
};
static ::_pbi::once_flag descriptor_table_ImitationState_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ImitationState_2eproto = {
    false, false, 762, descriptor_table_protodef_ImitationState_2eproto,
    "ImitationState.proto",
    &descriptor_table_ImitationState_2eproto_once, descriptor_table_ImitationState_2eproto_deps, 2, 6,
    schemas, file_default_instances, TableStruct_ImitationState_2eproto::offsets,
    file_level_metadata_ImitationState_2eproto, file_level_enum_descriptors_ImitationState_2eproto,
    file_level_service_descriptors_ImitationState_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ImitationState_2eproto_getter() {
  return &descriptor_table_ImitationState_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ImitationState_2eproto(&descriptor_table_ImitationState_2eproto);
namespace Schola {

// ===================================================================

ImitationAgentState_InfoEntry_DoNotUse::ImitationAgentState_InfoEntry_DoNotUse() {}
ImitationAgentState_InfoEntry_DoNotUse::ImitationAgentState_InfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void ImitationAgentState_InfoEntry_DoNotUse::MergeFrom(const ImitationAgentState_InfoEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata ImitationAgentState_InfoEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ImitationState_2eproto_getter, &descriptor_table_ImitationState_2eproto_once,
      file_level_metadata_ImitationState_2eproto[0]);
}

// ===================================================================

class ImitationAgentState::_Internal {
 public:
  static const ::Schola::Point& observations(const ImitationAgentState* msg);
  static const ::Schola::Point& actions(const ImitationAgentState* msg);
};

const ::Schola::Point&
ImitationAgentState::_Internal::observations(const ImitationAgentState* msg) {
  return *msg->_impl_.observations_;
}
const ::Schola::Point&
ImitationAgentState::_Internal::actions(const ImitationAgentState* msg) {
  return *msg->_impl_.actions_;
}
void ImitationAgentState::clear_observations() {
  if (GetArenaForAllocation() == nullptr && _impl_.observations_ != nullptr) {
    delete _impl_.observations_;
  }
  _impl_.observations_ = nullptr;
}
void ImitationAgentState::clear_actions() {
  if (GetArenaForAllocation() == nullptr && _impl_.actions_ != nullptr) {
    delete _impl_.actions_;
  }
  _impl_.actions_ = nullptr;
}
ImitationAgentState::ImitationAgentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &ImitationAgentState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.ImitationAgentState)
}
ImitationAgentState::ImitationAgentState(const ImitationAgentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ImitationAgentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.info_)*/{}
    , decltype(_impl_.observations_){nullptr}
    , decltype(_impl_.actions_){nullptr}
    , decltype(_impl_.reward_){}
    , decltype(_impl_.terminated_){}
    , decltype(_impl_.truncated_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.info_.MergeFrom(from._impl_.info_);
  if (from._internal_has_observations()) {
    _this->_impl_.observations_ = new ::Schola::Point(*from._impl_.observations_);
  }
  if (from._internal_has_actions()) {
    _this->_impl_.actions_ = new ::Schola::Point(*from._impl_.actions_);
  }
  ::memcpy(&_impl_.reward_, &from._impl_.reward_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.truncated_) -
    reinterpret_cast<char*>(&_impl_.reward_)) + sizeof(_impl_.truncated_));
  // @@protoc_insertion_point(copy_constructor:Schola.ImitationAgentState)
}

inline void ImitationAgentState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.info_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.observations_){nullptr}
    , decltype(_impl_.actions_){nullptr}
    , decltype(_impl_.reward_){0}
    , decltype(_impl_.terminated_){false}
    , decltype(_impl_.truncated_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ImitationAgentState::~ImitationAgentState() {
  // @@protoc_insertion_point(destructor:Schola.ImitationAgentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void ImitationAgentState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.info_.Destruct();
  _impl_.info_.~MapField();
  if (this != internal_default_instance()) delete _impl_.observations_;
  if (this != internal_default_instance()) delete _impl_.actions_;
}

void ImitationAgentState::ArenaDtor(void* object) {
  ImitationAgentState* _this = reinterpret_cast< ImitationAgentState* >(object);
  _this->_impl_.info_.Destruct();
}
void ImitationAgentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ImitationAgentState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.ImitationAgentState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.info_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.observations_ != nullptr) {
    delete _impl_.observations_;
  }
  _impl_.observations_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.actions_ != nullptr) {
    delete _impl_.actions_;
  }
  _impl_.actions_ = nullptr;
  ::memset(&_impl_.reward_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.truncated_) -
      reinterpret_cast<char*>(&_impl_.reward_)) + sizeof(_impl_.truncated_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImitationAgentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Schola.Point observations = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_observations(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float reward = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.reward_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool terminated = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.terminated_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool truncated = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.truncated_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, string> info = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.info_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .Schola.Point actions = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_actions(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImitationAgentState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.ImitationAgentState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Schola.Point observations = 1;
  if (this->_internal_has_observations()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::observations(this),
        _Internal::observations(this).GetCachedSize(), target, stream);
  }

  // float reward = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_reward = this->_internal_reward();
  uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_reward(), target);
  }

  // bool terminated = 3;
  if (this->_internal_terminated() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_terminated(), target);
  }

  // bool truncated = 4;
  if (this->_internal_truncated() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_truncated(), target);
  }

  // map<string, string> info = 5;
  if (!this->_internal_info().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = ImitationAgentState_InfoEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_info();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.ImitationAgentState.InfoEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.ImitationAgentState.InfoEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // .Schola.Point actions = 6;
  if (this->_internal_has_actions()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::actions(this),
        _Internal::actions(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.ImitationAgentState)
  return target;
}

size_t ImitationAgentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.ImitationAgentState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> info = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_info_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_info().begin();
      it != this->_internal_info().end(); ++it) {
    total_size += ImitationAgentState_InfoEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .Schola.Point observations = 1;
  if (this->_internal_has_observations()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.observations_);
  }

  // .Schola.Point actions = 6;
  if (this->_internal_has_actions()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.actions_);
  }

  // float reward = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_reward = this->_internal_reward();
  uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    total_size += 1 + 4;
  }

  // bool terminated = 3;
  if (this->_internal_terminated() != 0) {
    total_size += 1 + 1;
  }

  // bool truncated = 4;
  if (this->_internal_truncated() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImitationAgentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ImitationAgentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImitationAgentState::GetClassData() const { return &_class_data_; }


void ImitationAgentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ImitationAgentState*>(&to_msg);
  auto& from = static_cast<const ImitationAgentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.ImitationAgentState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.info_.MergeFrom(from._impl_.info_);
  if (from._internal_has_observations()) {
    _this->_internal_mutable_observations()->::Schola::Point::MergeFrom(
        from._internal_observations());
  }
  if (from._internal_has_actions()) {
    _this->_internal_mutable_actions()->::Schola::Point::MergeFrom(
        from._internal_actions());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_reward = from._internal_reward();
  uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    _this->_internal_set_reward(from._internal_reward());
  }
  if (from._internal_terminated() != 0) {
    _this->_internal_set_terminated(from._internal_terminated());
  }
  if (from._internal_truncated() != 0) {
    _this->_internal_set_truncated(from._internal_truncated());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImitationAgentState::CopyFrom(const ImitationAgentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.ImitationAgentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImitationAgentState::IsInitialized() const {
  return true;
}

void ImitationAgentState::InternalSwap(ImitationAgentState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.info_.InternalSwap(&other->_impl_.info_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ImitationAgentState, _impl_.truncated_)
      + sizeof(ImitationAgentState::_impl_.truncated_)
      - PROTOBUF_FIELD_OFFSET(ImitationAgentState, _impl_.observations_)>(
          reinterpret_cast<char*>(&_impl_.observations_),
          reinterpret_cast<char*>(&other->_impl_.observations_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ImitationAgentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ImitationState_2eproto_getter, &descriptor_table_ImitationState_2eproto_once,
      file_level_metadata_ImitationState_2eproto[1]);
}

// ===================================================================

ImitationEnvironmentState_AgentStatesEntry_DoNotUse::ImitationEnvironmentState_AgentStatesEntry_DoNotUse() {}
ImitationEnvironmentState_AgentStatesEntry_DoNotUse::ImitationEnvironmentState_AgentStatesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void ImitationEnvironmentState_AgentStatesEntry_DoNotUse::MergeFrom(const ImitationEnvironmentState_AgentStatesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata ImitationEnvironmentState_AgentStatesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ImitationState_2eproto_getter, &descriptor_table_ImitationState_2eproto_once,
      file_level_metadata_ImitationState_2eproto[2]);
}

// ===================================================================

class ImitationEnvironmentState::_Internal {
 public:
};

ImitationEnvironmentState::ImitationEnvironmentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &ImitationEnvironmentState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:Schola.ImitationEnvironmentState)
}
ImitationEnvironmentState::ImitationEnvironmentState(const ImitationEnvironmentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ImitationEnvironmentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.agent_states_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.agent_states_.MergeFrom(from._impl_.agent_states_);
  // @@protoc_insertion_point(copy_constructor:Schola.ImitationEnvironmentState)
}

inline void ImitationEnvironmentState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.agent_states_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ImitationEnvironmentState::~ImitationEnvironmentState() {
  // @@protoc_insertion_point(destructor:Schola.ImitationEnvironmentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void ImitationEnvironmentState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.agent_states_.Destruct();
  _impl_.agent_states_.~MapField();
}

void ImitationEnvironmentState::ArenaDtor(void* object) {
  ImitationEnvironmentState* _this = reinterpret_cast< ImitationEnvironmentState* >(object);
  _this->_impl_.agent_states_.Destruct();
}
void ImitationEnvironmentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ImitationEnvironmentState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.ImitationEnvironmentState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agent_states_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImitationEnvironmentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, .Schola.ImitationAgentState> agent_states = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.agent_states_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImitationEnvironmentState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.ImitationEnvironmentState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .Schola.ImitationAgentState> agent_states = 1;
  if (!this->_internal_agent_states().empty()) {
    using MapType = ::_pb::Map<std::string, ::Schola::ImitationAgentState>;
    using WireHelper = ImitationEnvironmentState_AgentStatesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_agent_states();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "Schola.ImitationEnvironmentState.AgentStatesEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.ImitationEnvironmentState)
  return target;
}

size_t ImitationEnvironmentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.ImitationEnvironmentState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .Schola.ImitationAgentState> agent_states = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_agent_states_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::Schola::ImitationAgentState >::const_iterator
      it = this->_internal_agent_states().begin();
      it != this->_internal_agent_states().end(); ++it) {
    total_size += ImitationEnvironmentState_AgentStatesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImitationEnvironmentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ImitationEnvironmentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImitationEnvironmentState::GetClassData() const { return &_class_data_; }


void ImitationEnvironmentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ImitationEnvironmentState*>(&to_msg);
  auto& from = static_cast<const ImitationEnvironmentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.ImitationEnvironmentState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.agent_states_.MergeFrom(from._impl_.agent_states_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImitationEnvironmentState::CopyFrom(const ImitationEnvironmentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.ImitationEnvironmentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImitationEnvironmentState::IsInitialized() const {
  return true;
}

void ImitationEnvironmentState::InternalSwap(ImitationEnvironmentState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.agent_states_.InternalSwap(&other->_impl_.agent_states_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ImitationEnvironmentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ImitationState_2eproto_getter, &descriptor_table_ImitationState_2eproto_once,
      file_level_metadata_ImitationState_2eproto[3]);
}

// ===================================================================

class ImitationTrainingState::_Internal {
 public:
};

ImitationTrainingState::ImitationTrainingState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.ImitationTrainingState)
}
ImitationTrainingState::ImitationTrainingState(const ImitationTrainingState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ImitationTrainingState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.environment_states_){from._impl_.environment_states_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Schola.ImitationTrainingState)
}

inline void ImitationTrainingState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.environment_states_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ImitationTrainingState::~ImitationTrainingState() {
  // @@protoc_insertion_point(destructor:Schola.ImitationTrainingState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ImitationTrainingState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.environment_states_.~RepeatedPtrField();
}

void ImitationTrainingState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ImitationTrainingState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.ImitationTrainingState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.environment_states_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImitationTrainingState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Schola.ImitationEnvironmentState environment_states = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_environment_states(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImitationTrainingState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.ImitationTrainingState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Schola.ImitationEnvironmentState environment_states = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_environment_states_size()); i < n; i++) {
    const auto& repfield = this->_internal_environment_states(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.ImitationTrainingState)
  return target;
}

size_t ImitationTrainingState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.ImitationTrainingState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Schola.ImitationEnvironmentState environment_states = 1;
  total_size += 1UL * this->_internal_environment_states_size();
  for (const auto& msg : this->_impl_.environment_states_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImitationTrainingState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ImitationTrainingState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImitationTrainingState::GetClassData() const { return &_class_data_; }


void ImitationTrainingState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ImitationTrainingState*>(&to_msg);
  auto& from = static_cast<const ImitationTrainingState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.ImitationTrainingState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.environment_states_.MergeFrom(from._impl_.environment_states_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImitationTrainingState::CopyFrom(const ImitationTrainingState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.ImitationTrainingState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImitationTrainingState::IsInitialized() const {
  return true;
}

void ImitationTrainingState::InternalSwap(ImitationTrainingState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.environment_states_.InternalSwap(&other->_impl_.environment_states_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ImitationTrainingState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ImitationState_2eproto_getter, &descriptor_table_ImitationState_2eproto_once,
      file_level_metadata_ImitationState_2eproto[4]);
}

// ===================================================================

class ImitationState::_Internal {
 public:
  static const ::Schola::ImitationTrainingState& training_state(const ImitationState* msg);
  static const ::Schola::InitialState& initial_state(const ImitationState* msg);
};

const ::Schola::ImitationTrainingState&
ImitationState::_Internal::training_state(const ImitationState* msg) {
  return *msg->_impl_.optional_training_state_.training_state_;
}
const ::Schola::InitialState&
ImitationState::_Internal::initial_state(const ImitationState* msg) {
  return *msg->_impl_.optional_initial_state_.initial_state_;
}
void ImitationState::set_allocated_training_state(::Schola::ImitationTrainingState* training_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_optional_training_state();
  if (training_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(training_state);
    if (message_arena != submessage_arena) {
      training_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, training_state, submessage_arena);
    }
    set_has_training_state();
    _impl_.optional_training_state_.training_state_ = training_state;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.ImitationState.training_state)
}
void ImitationState::set_allocated_initial_state(::Schola::InitialState* initial_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_optional_initial_state();
  if (initial_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(initial_state));
    if (message_arena != submessage_arena) {
      initial_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, initial_state, submessage_arena);
    }
    set_has_initial_state();
    _impl_.optional_initial_state_.initial_state_ = initial_state;
  }
  // @@protoc_insertion_point(field_set_allocated:Schola.ImitationState.initial_state)
}
void ImitationState::clear_initial_state() {
  if (_internal_has_initial_state()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.optional_initial_state_.initial_state_;
    }
    clear_has_optional_initial_state();
  }
}
ImitationState::ImitationState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Schola.ImitationState)
}
ImitationState::ImitationState(const ImitationState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ImitationState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.optional_training_state_){}
    , decltype(_impl_.optional_initial_state_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_optional_training_state();
  switch (from.optional_training_state_case()) {
    case kTrainingState: {
      _this->_internal_mutable_training_state()->::Schola::ImitationTrainingState::MergeFrom(
          from._internal_training_state());
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  clear_has_optional_initial_state();
  switch (from.optional_initial_state_case()) {
    case kInitialState: {
      _this->_internal_mutable_initial_state()->::Schola::InitialState::MergeFrom(
          from._internal_initial_state());
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Schola.ImitationState)
}

inline void ImitationState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.optional_training_state_){}
    , decltype(_impl_.optional_initial_state_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_optional_training_state();
  clear_has_optional_initial_state();
}

ImitationState::~ImitationState() {
  // @@protoc_insertion_point(destructor:Schola.ImitationState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ImitationState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_optional_training_state()) {
    clear_optional_training_state();
  }
  if (has_optional_initial_state()) {
    clear_optional_initial_state();
  }
}

void ImitationState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ImitationState::clear_optional_training_state() {
// @@protoc_insertion_point(one_of_clear_start:Schola.ImitationState)
  switch (optional_training_state_case()) {
    case kTrainingState: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.optional_training_state_.training_state_;
      }
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = OPTIONAL_TRAINING_STATE_NOT_SET;
}

void ImitationState::clear_optional_initial_state() {
// @@protoc_insertion_point(one_of_clear_start:Schola.ImitationState)
  switch (optional_initial_state_case()) {
    case kInitialState: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.optional_initial_state_.initial_state_;
      }
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[1] = OPTIONAL_INITIAL_STATE_NOT_SET;
}


void ImitationState::Clear() {
// @@protoc_insertion_point(message_clear_start:Schola.ImitationState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_optional_training_state();
  clear_optional_initial_state();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ImitationState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Schola.ImitationTrainingState training_state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_training_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Schola.InitialState initial_state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_initial_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ImitationState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Schola.ImitationState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Schola.ImitationTrainingState training_state = 1;
  if (_internal_has_training_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::training_state(this),
        _Internal::training_state(this).GetCachedSize(), target, stream);
  }

  // .Schola.InitialState initial_state = 2;
  if (_internal_has_initial_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::initial_state(this),
        _Internal::initial_state(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Schola.ImitationState)
  return target;
}

size_t ImitationState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Schola.ImitationState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (optional_training_state_case()) {
    // .Schola.ImitationTrainingState training_state = 1;
    case kTrainingState: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.optional_training_state_.training_state_);
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  switch (optional_initial_state_case()) {
    // .Schola.InitialState initial_state = 2;
    case kInitialState: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.optional_initial_state_.initial_state_);
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ImitationState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ImitationState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ImitationState::GetClassData() const { return &_class_data_; }


void ImitationState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ImitationState*>(&to_msg);
  auto& from = static_cast<const ImitationState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Schola.ImitationState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.optional_training_state_case()) {
    case kTrainingState: {
      _this->_internal_mutable_training_state()->::Schola::ImitationTrainingState::MergeFrom(
          from._internal_training_state());
      break;
    }
    case OPTIONAL_TRAINING_STATE_NOT_SET: {
      break;
    }
  }
  switch (from.optional_initial_state_case()) {
    case kInitialState: {
      _this->_internal_mutable_initial_state()->::Schola::InitialState::MergeFrom(
          from._internal_initial_state());
      break;
    }
    case OPTIONAL_INITIAL_STATE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ImitationState::CopyFrom(const ImitationState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Schola.ImitationState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImitationState::IsInitialized() const {
  return true;
}

void ImitationState::InternalSwap(ImitationState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.optional_training_state_, other->_impl_.optional_training_state_);
  swap(_impl_.optional_initial_state_, other->_impl_.optional_initial_state_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
  swap(_impl_._oneof_case_[1], other->_impl_._oneof_case_[1]);
}

::PROTOBUF_NAMESPACE_ID::Metadata ImitationState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ImitationState_2eproto_getter, &descriptor_table_ImitationState_2eproto_once,
      file_level_metadata_ImitationState_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Schola
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Schola::ImitationAgentState_InfoEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::ImitationAgentState_InfoEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::ImitationAgentState_InfoEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::ImitationAgentState*
Arena::CreateMaybeMessage< ::Schola::ImitationAgentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::ImitationAgentState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::ImitationEnvironmentState_AgentStatesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::ImitationEnvironmentState*
Arena::CreateMaybeMessage< ::Schola::ImitationEnvironmentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::ImitationEnvironmentState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::ImitationTrainingState*
Arena::CreateMaybeMessage< ::Schola::ImitationTrainingState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::ImitationTrainingState >(arena);
}
template<> PROTOBUF_NOINLINE ::Schola::ImitationState*
Arena::CreateMaybeMessage< ::Schola::ImitationState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Schola::ImitationState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
