// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: OfflineConnector.proto

#include "OfflineConnector.pb.h"
#include "OfflineConnector.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Schola {

static const char* OfflineConnectorService_method_names[] = {
  "/Schola.OfflineConnectorService/RequestData",
  "/Schola.OfflineConnectorService/RequestDefinition",
  "/Schola.OfflineConnectorService/StartConnector",
};

std::unique_ptr< OfflineConnectorService::Stub> OfflineConnectorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OfflineConnectorService::Stub> stub(new OfflineConnectorService::Stub(channel, options));
  return stub;
}

OfflineConnectorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestData_(OfflineConnectorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestDefinition_(OfflineConnectorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartConnector_(OfflineConnectorService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OfflineConnectorService::Stub::RequestData(::grpc::ClientContext* context, const ::Schola::OfflineDataRequest& request, ::Schola::BatchedOfflineData* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Schola::OfflineDataRequest, ::Schola::BatchedOfflineData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestData_, context, request, response);
}

void OfflineConnectorService::Stub::async::RequestData(::grpc::ClientContext* context, const ::Schola::OfflineDataRequest* request, ::Schola::BatchedOfflineData* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Schola::OfflineDataRequest, ::Schola::BatchedOfflineData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestData_, context, request, response, std::move(f));
}

void OfflineConnectorService::Stub::async::RequestData(::grpc::ClientContext* context, const ::Schola::OfflineDataRequest* request, ::Schola::BatchedOfflineData* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Schola::BatchedOfflineData>* OfflineConnectorService::Stub::PrepareAsyncRequestDataRaw(::grpc::ClientContext* context, const ::Schola::OfflineDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Schola::BatchedOfflineData, ::Schola::OfflineDataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Schola::BatchedOfflineData>* OfflineConnectorService::Stub::AsyncRequestDataRaw(::grpc::ClientContext* context, const ::Schola::OfflineDataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OfflineConnectorService::Stub::RequestDefinition(::grpc::ClientContext* context, const ::Schola::OfflineDefinitionRequest& request, ::Schola::OfflineDefinition* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Schola::OfflineDefinitionRequest, ::Schola::OfflineDefinition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestDefinition_, context, request, response);
}

void OfflineConnectorService::Stub::async::RequestDefinition(::grpc::ClientContext* context, const ::Schola::OfflineDefinitionRequest* request, ::Schola::OfflineDefinition* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Schola::OfflineDefinitionRequest, ::Schola::OfflineDefinition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestDefinition_, context, request, response, std::move(f));
}

void OfflineConnectorService::Stub::async::RequestDefinition(::grpc::ClientContext* context, const ::Schola::OfflineDefinitionRequest* request, ::Schola::OfflineDefinition* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestDefinition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Schola::OfflineDefinition>* OfflineConnectorService::Stub::PrepareAsyncRequestDefinitionRaw(::grpc::ClientContext* context, const ::Schola::OfflineDefinitionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Schola::OfflineDefinition, ::Schola::OfflineDefinitionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestDefinition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Schola::OfflineDefinition>* OfflineConnectorService::Stub::AsyncRequestDefinitionRaw(::grpc::ClientContext* context, const ::Schola::OfflineDefinitionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestDefinitionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OfflineConnectorService::Stub::StartConnector(::grpc::ClientContext* context, const ::Schola::OfflineConnectorStartRequest& request, ::Schola::OfflineConnectorStartResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Schola::OfflineConnectorStartRequest, ::Schola::OfflineConnectorStartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartConnector_, context, request, response);
}

void OfflineConnectorService::Stub::async::StartConnector(::grpc::ClientContext* context, const ::Schola::OfflineConnectorStartRequest* request, ::Schola::OfflineConnectorStartResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Schola::OfflineConnectorStartRequest, ::Schola::OfflineConnectorStartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartConnector_, context, request, response, std::move(f));
}

void OfflineConnectorService::Stub::async::StartConnector(::grpc::ClientContext* context, const ::Schola::OfflineConnectorStartRequest* request, ::Schola::OfflineConnectorStartResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartConnector_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Schola::OfflineConnectorStartResponse>* OfflineConnectorService::Stub::PrepareAsyncStartConnectorRaw(::grpc::ClientContext* context, const ::Schola::OfflineConnectorStartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Schola::OfflineConnectorStartResponse, ::Schola::OfflineConnectorStartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartConnector_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Schola::OfflineConnectorStartResponse>* OfflineConnectorService::Stub::AsyncStartConnectorRaw(::grpc::ClientContext* context, const ::Schola::OfflineConnectorStartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartConnectorRaw(context, request, cq);
  result->StartCall();
  return result;
}

OfflineConnectorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OfflineConnectorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OfflineConnectorService::Service, ::Schola::OfflineDataRequest, ::Schola::BatchedOfflineData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OfflineConnectorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Schola::OfflineDataRequest* req,
             ::Schola::BatchedOfflineData* resp) {
               return service->RequestData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OfflineConnectorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OfflineConnectorService::Service, ::Schola::OfflineDefinitionRequest, ::Schola::OfflineDefinition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OfflineConnectorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Schola::OfflineDefinitionRequest* req,
             ::Schola::OfflineDefinition* resp) {
               return service->RequestDefinition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OfflineConnectorService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OfflineConnectorService::Service, ::Schola::OfflineConnectorStartRequest, ::Schola::OfflineConnectorStartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OfflineConnectorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Schola::OfflineConnectorStartRequest* req,
             ::Schola::OfflineConnectorStartResponse* resp) {
               return service->StartConnector(ctx, req, resp);
             }, this)));
}

OfflineConnectorService::Service::~Service() {
}

::grpc::Status OfflineConnectorService::Service::RequestData(::grpc::ServerContext* context, const ::Schola::OfflineDataRequest* request, ::Schola::BatchedOfflineData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OfflineConnectorService::Service::RequestDefinition(::grpc::ServerContext* context, const ::Schola::OfflineDefinitionRequest* request, ::Schola::OfflineDefinition* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OfflineConnectorService::Service::StartConnector(::grpc::ServerContext* context, const ::Schola::OfflineConnectorStartRequest* request, ::Schola::OfflineConnectorStartResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Schola

